'use client';
import React, { createContext, useContext, useState, useMemo } from 'react';

const translations = {
  EN: {
    brand: "The Haridasa Kosha",
    navLibrary: "Library",
    navComposers: "Haridasaru",
    navLearn: "Learn",
    navDailyWisdom: "Daily Wisdom",
    navAskAI: "Ask AI",
    navAbout: "About",
    composersPageTitle: "Haridasa Composers",
    composersPageDesc: "Explore the divine voices of the Haridasa tradition.",
    searchComposers: "Search composers...",
    tblName: "Composer Name",
    tblAnkita: "Ankita nama",
    tblPeriod: "Year",
    tblCount: "Composition count",
    tblActions: "Actions",
    viewProfile: "View Profile",
    Compositions: "Compositions",
    "Harapanahalli Bhimavva": "Harapanahalli Bhimavva",
    "Bhakti": "Bhakti",
    "Jnana": "Jnana",
    "Vairagya": "Vairagya",
    "Guru Mahima": "Guru Mahima",
    "Nama Mahima": "Nama Mahima",
    "Krishna Bhakti": "Krishna Bhakti",
    "Rama Bhakti": "Rama Bhakti",
    "Madhwa Siddhanta": "Madhwa Siddhanta",
    "Sripadarajaru": "Sripadarajaru",
    "Narahari Tirtharu": "Narahari Tirtharu",
    "Vadiraja Tirtharu": "Vadiraja Tirtharu",
    "Guru Jagannatha Dasaru": "Guru Jagannatha Dasaru",
    "Srinivasa Dasaru": "Srinivasa Dasaru",
    "Venkatesha Dasaru": "Venkatesha Dasaru",
    "Subbanna Dasaru": "Subbanna Dasaru",
    "Ugabhoga Narayana Dasaru": "Ugabhoga Narayana Dasaru",
    "Madhwapati Dasaru": "Madhwapati Dasaru",
    "Vishnu Dasaru": "Vishnu Dasaru",
    "Vyasatirtharu": "Vyasatirtharu",
    "Krishnapriya Dasaru": "Krishnapriya Dasaru",
    "Raghavendra Dasaru": "Raghavendra Tirtharu",
    "Raghavendra Tirtharu": "Raghavendra Tirtharu",
    "Achyuta Dasaru": "Achyuta Dasaru",
    "Narahari Dasaru": "Narahari Dasaru",
    "Gopala Dasaru": "Gopala Dasaru",
    "Purandara Dasaru": "Purandara Dasaru",
    "Kanaka Dasaru": "Kanaka Dasaru",
    "Vijaya Dasaru": "Vijaya Dasaru",
    "Helavanakatte Giriyamma": "Helavanakatte Giriyamma",
    "Jagannatha Dasaru": "Jagannatha Dasaru",
    "Prasanna Venkata Dasaru": "Prasanna Venkata Dasaru",
    "Mohana Dasaru": "Mohana Dasaru",
    "Pranesha Dasaru": "Pranesha Dasaru",
    "Venugopala Dasaru": "Venugopala Dasaru",
    "Mahipati Dasaru": "Mahipati Dasaru",
    "Govinda Dasaru": "Govinda Dasaru",
    "Lakshmipati Dasaru": "Lakshmipati Dasaru",
    "Satyabodha Dasaru": "Satyabodha Dasaru",
    
    // Homepage
    missionEyebrow: "The Mission",
    missionTitle: "Preserving the Voice of Devotion",
    missionDesc: "The Haridasa Kosha is a digital repository dedicated to the preservation and study of Dasa Sahitya—the devotional literature of the Haridasaru of Karnataka.",
    livingTradition: "A Living Tradition",
    livingTraditionDesc: "Founded on the principles of Dvaita philosophy, the Haridasa movement democratized spiritual knowledge through song. From the foundational works of Sri Narahari Tirtha to the prolific legacy of Purandara Dasa, this platform serves as a bridge for the modern world to access this profound wisdom.",
    foundations: "Understand the philosophical foundations of the Dasa Sahitya.",
    verifiedKeertanas: "Access verified Keertanas with accurate scriptural context.",
    discoverStories: "Discover the life stories of over 150 documented Haridasaru.",
    studyStructures: "Study the musical structures of the early Haridasa compositions.",
    paramparaTitle: "The Haridasa Parampara",
    paramparaDesc: "Trace the 800-year history of the devotional movement founded by Sri Narahari Tirtha and flourished under the Vijayanagara Empire.",
    archiveTitle: "Dasa Sahitya Archive",
    archiveDesc: "Access thousands of Keertanas, Suladis, and Ugabhogas with accurate Kannada lyrics, phonetic transliteration, and English meanings.",
    scholarlyTitle: "Scholarly Research",
    scholarlyDesc: "Explore compositions categorized by Raga, Tala, Ankita, and Prameya to understand the philosophical depth of Dvaita Vedanta.",
    keyFeatures: "Key Features",
    structuredPath: "A Structured Path to Spiritual Knowledge",
    pathDesc: "The Kosha is organized to facilitate both devotional practice and academic research, providing multiple lenses to view the Haridasa tradition.",
    historicalAuthenticity: "Historical Authenticity",
    historicalDesc: "Every profile is cross-referenced with traditional records to provide accurate lineages, time periods, and biographical details of the Haridasaru.",
    musicalHeritage: "Musical Heritage",
    musicalHeritageDesc: "Discover the foundation of Carnatic music through the works of Purandara Dasa, the Pitamaha, and other stalwarts who shaped its pedagogy.",
    universalAccess: "Universal Access",
    universalAccessDesc: "Built for the modern seeker, researcher, and devotee, bridging the gap between ancient manuscript traditions and digital convenience.",
    haridasaruTitle: "Haridasaru",
    saintsSoil: "The Saints of the Soil",
    saintsSoilDesc: "Meet the devotional reformers who travelled the length and breadth of the land, spreading the message of love and surrender.",
    exploreAllHaridasaru: "Explore All Haridasaru",
    devotionalContext: "Devotional Context",
    exploreByDeity: "Explore by Deity",
    deityDesc: "The Haridasa compositions are predominantly addressed to Lord Vittala of Pandharpur and various forms of Lord Vishnu. Explore works dedicated to specific deities.",
    dailyWisdomTitle: "Daily Dasa Vani",
    dailyWisdomDesc: "A fresh devotional reflection for today from the archive.",
    startingPoint: "A Starting Point",
    journeyKeertana: "Begin Your Journey with a Single Keertana",
    journeyDesc: "Every composition is a door to the profound spiritual world of the Haridasaru. Start with a random work and explore its depth.",
    modernSeeker: "A Guide for the Modern Seeker",
    modernSeekerDesc: "If you are new to the tradition, we recommend starting with the life of Sri Purandara Dasa, often called the Father of Carnatic Music. From there, you can explore themes like surrender (Sharanagati), social reform, and philosophical enquiry (Prameya).",
    browseArchive: "Browse Archive",
    learnHistory: "Learn the History",
    insideArchive: "Inside the Archive",
    biographiesCount: "Biographies of 150+ Haridasaru across centuries",
    authenticLyrics: "Authentic Kannada lyrics with phonetic transliteration",
    philosophicalMeanings: "Deep philosophical meanings and English translations",
    categorization: "Categorization by Raga, Tala, and Ankita Nama",
    academicDevotional: "Structured for both academic and devotional study",

    // Hero
    heroEyebrow: "The Haridasa Kosha",
    heroTitle: "A gateway to the Haridasa tradition.",
    heroDesc: "Explore verified Haridasa profiles, read compositions with Kannada lyrics and meaning, and discover the spiritual depth of the Dasa Sahitya.",
    quickSearch: "Quick Search",
    searchPlaceholder: "Search by composer, song title, or deity...",
    exploreCompositions: "Explore Compositions",
    meetHaridasaru: "Meet the Haridasaru",
    haridasaruDocumented: "Haridasaru documented",
    compositionsCatalogued: "Compositions catalogued",
    languagesSupported: "Languages supported",
    howToUse: "How to use this Kosha",
    journeyStart: "Start Your Journey",
    learnStep: "Learn",
    learnStepDesc: "Study biographies and lineage of Haridasaru.",
    readStep: "Read",
    readStepDesc: "Lyrics, transliteration, and meanings in one place.",
    searchStep: "Search",
    searchStepDesc: "Find by composer, deity, first line, or theme.",
    forNewcomers: "For Newcomers",
    forNewcomersDesc: "Start with a profile, then explore compositions.",
    forScholars: "For Scholars",
    forScholarsDesc: "Use search and themes for deep research.",

    // About Page
    ourVision: "Our Vision",
    visionDesc: "To create a comprehensive, accessible, and scholarly-vetted digital repository that bridges the gap between ancient manuscript traditions and modern seekers.",
    whyWeExist: "Why We Exist",
    whyWeExistDesc: "The Dasa Sahitya is not just literature; it is a profound spiritual, musical, and philosophical heritage that has sustained communities for centuries. We exist to ensure this wisdom remains vibrant.",
    digitalArchiving: "Digital Archiving",
    digitalArchivingDesc: "Converting rare manuscripts and disparate editions into a unified, searchable, and structured database.",
    communityEngagement: "Community Engagement",
    communityEngagementDesc: "Building a platform that invites scholars, students, and devotees to learn, discuss, and contribute to the collective understanding.",
    aboutEyebrow: "Our Initiative",
    aboutTitle: "The Haridasa Kosha Project",
    aboutLead: "A collaborative effort to digitize, translate, and preserve the complete works of the Haridasaru for future generations.",
    historyTitle: "Rooted in the 13th Century",
    historyDesc1: "The Haridasa Sahitya represents a unique blend of high philosophy and accessible poetry. Originating with Sri Narahari Tirtha and Sri Sripadaraja, the movement reached its zenith during the era of the Vijayanagara Empire.",
    historyDesc2: "Our project aims to bring this vast body of work out of fading manuscripts and into a digital format that is searchable, readable, and understandable for the modern audience.",
    methodologyTitle: "Our Methodology",
    methodologyDesc: "We maintain a rigorous process for archival and presentation to ensure that the sanctity and accuracy of the compositions are preserved.",
    archivalIntegrity: "Archival Integrity",
    archivalIntegrityDesc: "We use primary sources and multiple editions to verify the lyrics and authorship of each composition.",
    scholarlyVetting: "Scholarly Vetting",
    scholarlyVettingDesc: "Our translations and meanings are reviewed by scholars of Dvaita Vedanta and Dasa Sahitya.",
    digitalPreservation: "Digital Preservation",
    digitalPreservationDesc: "Data is structured to be future-proof and accessible via open APIs for researchers worldwide.",
    joinMissionTitle: "Join Our Mission",
    joinMissionDesc: "Whether you are a scholar, a singer, or a devotee, there are many ways to contribute to this growing digital library.",
    contributeBtn: "Contribute Now",
    contactBtn: "Contact Us",
    composers: "Composers",
    compositions: "Compositions",
    contributors: "Contributors",
    yearsOfHistory: "Years of History",

    // Featured
    featuredEyebrow: "Handpicked for you",
    featuredTitle: "Featured Compositions",
    featuredDesc: "Explore beloved devotional melodies that have guided seekers for generations.",
    viewEntireCollection: "View Entire Collection",

    // Compositions Page
    compositionsHeading: "Haridasa Compositions",
    compositionsSubtitle: "Explore the largest searchable collection of devotional compositions from the Dvaita tradition.",
    statsCompositions: "Compositions",
    statsHaridasas: "Haridasas",
    statsRagas: "Ragas",
    statsAnkitas: "Ankitas",
    popularSearches: "Popular Searches",
    exploreByHaridasa: "Explore by Haridasa",
    featuredCompositionOfTheDay: "Featured Composition of the Day",
    readComposition: "Read Composition",
    quickFilters: "Quick Filters",
    all: "All",
    moreFilters: "More Filters",
    grid: "Grid",
    list: "List",
    read: "Read",

    aiMeaningfulWelcome: "Namaste. Welcome to The Haridasa Kosha. I am your AI companion, here to help you discover the divine poetry and profound philosophy of the Dasa Sahitya. Ask me about the lives of the Haridasaru, the meaning of a Keertana, or the core tenets of Dvaita Vedanta.",
    aiErrorMessage: "Sorry, I am having trouble connecting to my knowledge base.",
    enterSearchQuery: "Enter a search query to find compositions and composers.",
    noResultsFound: "No results found for",
    tryDifferentSearch: "Try a different search.",

    // Contribute Page
    contributeTitle: "Contribute to The Haridasa Kosha",
    contributeSubtitle: "Join our mission to preserve, digitize, and share the divine wisdom of the Haridasaru.",
    proofreading: "Proofreading",
    proofreadingDesc: "Review lyrics and transcriptions to ensure textual accuracy.",
    transcription: "Transcription",
    transcriptionDesc: "Help transcribe palm-leaf manuscripts into digital formats.",
    translation: "Translation",
    translationDesc: "Translate devotional meanings into English and other languages.",
    technicalSupport: "Technical Support",
    technicalSupportDesc: "Contribute your technical expertise to improve our archive.",
    getStartedBtn: "Get Started",
    noDailyWisdomAvailable: "No Daily Wisdom available.",
    loading: "Loading...",
    haridasa: "Haridasa",
    historical: "Historical",
    exploreProfile: "Explore profile",
    open: "Open",
    defaultBio: "A revered Haridasa whose compositions continue to guide spiritual seekers.",
    archivalEntry: "Archival Entry",
    primaryRecord: "Primary Record",
    master: "Master",
    subject: "Subject",
    vittala: "Vittala",
    krishna: "Krishna",
    rama: "Rama",
    lakshmi: "Lakshmi",
    narasimha: "Narasimha",
    hanuman: "Hanuman",
    srinivasa: "Srinivasa",
    shiva: "Shiva",
    "Purandara Dasa": "Purandara Dasa",
    "Kanaka Dasa": "Kanaka Dasa",
    "Vittala": "Vittala",
    "Krishna": "Krishna",
    "Ugabhoga": "Ugabhoga",
    filters: "Filters",
    clearAll: "Clear All",
    composerLabel: "Composer",
    deityLabel: "Deity",
    ankitaLabel: "Ankita",
    ragaLabel: "Raga",
    talaLabel: "Tala",
    tagLabel: "Tags",
    allComposers: "All Composers",
    allDeities: "All Deities",
    allAnkitas: "All Ankitas",
    allRagas: "All Ragas",
    allTalas: "All Talas",
    allTags: "All Tags",
    kannadaLyrics: "Kannada Lyrics",
    englishTranslation: "English Translation",
    audioRecordings: "Audio Recordings",
    play: "Play",
    prototypeWarning: "Early prototype - functionalities may be limited.",
    askAiPrototypeWarning: "AI may not work as expected due to limited implementation."
    },
    KN: {
    brand: "ಹರಿದಾಸ ಕೋಶ",
    navLibrary: "ಗ್ರಂಥಾಲಯ",
    navComposers: "ಹರಿದಾಸರು",
    navLearn: "ಕಲಿಯಿರಿ",
    navDailyWisdom: "ದೈನಂದಿನ ಜ್ಞಾನ",
    navAskAI: "AI ಅನ್ನು ಕೇಳಿ",
    navAbout: "ನಮ್ಮ ಬಗ್ಗೆ",
    composersPageTitle: "ಹರಿದಾಸರು",
    composersPageDesc: "ಹರಿದಾಸ ಪರಂಪರೆಯ ದೈವಿಕ ಧ್ವನಿಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    searchComposers: "ಹರಿದಾಸರನ್ನು ಹುಡುಕಿ...",
    tblName: "ಹರಿದಾಸರ ಹೆಸರು",
    tblAnkita: "ಅಂಕಿತ ನಾಮ",
    tblPeriod: "ಕಾಲ",
    tblCount: "ರಚನೆಗಳ ಸಂಖ್ಯೆ",
    tblActions: "ಕ್ರಿಯೆಗಳು",
    viewProfile: "ಪ್ರೊಫೈಲ್ ನೋಡಿ",
    Compositions: "ರಚನೆಗಳು",
    "Harapanahalli Bhimavva": "ಹರಪನಹಳ್ಳಿ ಭೀಮವ್ವ",
    "Bhakti": "ಭಕ್ತಿ",
    "Jnana": "ಜ್ಞಾನ",
    "Vairagya": "ವೈರಾಗ್ಯ",
    "Guru Mahima": "ಗುರು ಮಹಿಮೆ",
    "Nama Mahima": "ನಾಮ ಮಹಿಮೆ",
    "Krishna Bhakti": "ಕೃಷ್ಣ ಭಕ್ತಿ",
    "Rama Bhakti": "ರಾಮ ಭಕ್ತಿ",
    "Madhwa Siddhanta": "ಮಧ್ವ ಸಿದ್ಧಾಂತ",
    "Sripadarajaru": "ಶ್ರೀಪಾದರಾಜರು",
    "Narahari Tirtharu": "ನರಹರಿ ತೀರ್ಥರು",
    "Vadiraja Tirtharu": "ವಾದಿರಾಜ ತೀರ್ಥರು",
    "Guru Jagannatha Dasaru": "ಗುರು ಜಗನ್ನಾಥದಾಸರು",
    "Srinivasa Dasaru": "ಶ್ರೀನಿವಾಸದಾಸರು",
    "Venkatesha Dasaru": "ವೆಂಕಟೇಶದಾಸರು",
    "Subbanna Dasaru": "ಸುಬ್ಬಣ್ಣದಾಸರು",
    "Ugabhoga Narayana Dasaru": "ಉಗಾಭೋಗ nಾರಾಯಣದಾಸರು",
    "Madhwapati Dasaru": "ಮಧ್ವಪತಿದಾಸರು",
    "Vishnu Dasaru": "ವಿಷ್ಣುದಾಸರು",
    "Vyasatirtharu": "ವ್ಯಾಸತೀರ್ಥರು",
    "Krishnapriya Dasaru": "ಕೃಷ್ಣಪ್ರಿಯದಾಸರು",
    "Raghavendra Dasaru": "ರಾಘವೇಂದ್ರ ತೀರ್ಥರು",
    "Raghavendra Tirtharu": "ರಾಘವೇಂದ್ರ ತೀರ್ಥರು",
    "Achyuta Dasaru": "ಅಚ್ಯುತದಾಸರು",
    "Narahari Dasaru": "ನರಹರಿದಾಸರು",
    "Gopala Dasaru": "ಗೋಪಾಲದಾಸರು",
    "Purandara Dasaru": "ಪುರಂದರದಾಸರು",
    "Kanaka Dasaru": "ಕನಕದಾಸರು",
    "Vijaya Dasaru": "ವಿಜಯದಾಸರು",
    "Helavanakatte Giriyamma": "ಹೆಳವನಕಟ್ಟೆ ಗಿರಿಯಮ್ಮ",
    "Jagannatha Dasaru": "ಜಗನ್ನಾಥದಾಸರು",
    "Prasanna Venkata Dasaru": "ಪ್ರಸನ್ನ ವೆಂಕಟದಾಸರು",
    "Mohana Dasaru": "ಮೋಹನದಾಸರು",
    "Pranesha Dasaru": "ಪ್ರಾಣೇಶದಾಸರು",
    "Venugopala Dasaru": "ವೇಣುಗೋಪಾಲದಾಸರು",
    "Mahipati Dasaru": "ಮಹೀಪತಿದಾಸರು",
    "Govinda Dasaru": "ಗೋವಿಂದದಾಸರು",
    "Lakshmipati Dasaru": "ಲಕ್ಷ್ಮೀಪತಿದಾಸರು",
    "Satyabodha Dasaru": "ಸತ್ಯಬೋಧದಾಸರು",

    // Homepage (Kannada)
    missionEyebrow: "ಧ್ಯೇಯ",
    missionTitle: "ಭಕ್ತಿಯ ದನಿಯನ್ನು ಸಂರಕ್ಷಿಸುವುದು",
    missionDesc: "ಹರಿದಾಸ ಕೋಶವು ಕರ್ನಾಟಕದ ಹರಿದಾಸರ ಭಕ್ತಿ ಸಾಹಿತ್ಯವನ್ನು ಸಂರಕ್ಷಿಸಲು ಮತ್ತು ಅಧ್ಯಯನ ಮಾಡಲು ಮೀಸಲಾದ ಡಿಜಿಟಲ್ ಭಂಡಾರವಾಗಿದೆ.",
    livingTradition: "ಸಜೀವ ಪರಂಪರೆ",
    livingTraditionDesc: "ದ್ವೈತ ತತ್ವಶಾಸ್ತ್ರದ ತಳಹದಿಯ ಮೇಲೆ ಸ್ಥಾಪಿತವಾದ ಹರಿದಾಸ ಚಳುವಳಿಯು ಹಾರ್ದಿಕ ಭಕ್ತಿಯ ಮೂಲಕ ಆಧ್ಯಾತ್ಮಿಕ ಜ್ಞಾನವನ್ನು ಜನಸಾಮಾನ್ಯರಿಗೆ ತಲುಪಿಸಿತು.",
    foundations: "ದಾಸ ಸಾಹಿತ್ಯದ ತಾತ್ವಿಕ ಅಡಿಪಾಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
    verifiedKeertanas: "ನಿಖರವಾದ ಶಾಸ್ತ್ರೀಯ ಹಿನ್ನೆಲೆಯೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿದ ಕೀರ್ತನೆಗಳನ್ನು ಓದಿ.",
    discoverStories: "೧೫೦ ಕ್ಕೂ ಹೆಚ್ಚು ದಾಖಲಾದ ಹರಿದಾಸರ ಜೀವನ ಚರಿತ್ರೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    studyStructures: "ಆರಂಭಿಕ ಹರಿದಾಸ ರಚನೆಗಳ ಸಂಗೀತ ರಚನೆಗಳನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ.",
    paramparaTitle: "ಹರಿದಾಸ ಪರಂಪರೆ",
    paramparaDesc: "ಶ್ರೀ ನರಹರಿ ತೀರ್ಥರಿಂದ ಸ್ಥಾಪಿತವಾಗಿ ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಅಡಿಯಲ್ಲಿ ಪ್ರವರ್ಧಮಾನಕ್ಕೆ ಬಂದ ೮೦೦ ವರ್ಷಗಳ ಭಕ್ತಿ ಚಳುವಳಿಯ ಇತಿಹಾಸವನ್ನು ಪತ್ತೆಹಚ್ಚಿ.",
    archiveTitle: "ದಾಸ ಸಾಹಿತ್ಯ ಭಂಡಾರ",
    archiveDesc: "ಸಾವಿರಾರು ಕೀರ್ತನೆಗಳು, ಸುಳಾದಿಗಳು ಮತ್ತು ಉಗಾಭೋಗಗಳನ್ನು ಕನ್ನಡ ಸಾಹಿತ್ಯ, ಲಿಪ್ಯಂತರ ಮತ್ತು ಇಂಗ್ಲಿಷ್ ಅರ್ಥಗಳೊಂದಿಗೆ ಪ್ರವೇಶಿಸಿ.",
    scholarlyTitle: "ವಿದ್ವತ್ಪೂರ್ಣ ಸಂಶೋಧನೆ",
    scholarlyDesc: "ದ್ವೈತ ವೇದಾಂತದ ತಾತ್ವಿಕ ಆಳವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ರಾಗ, ತಾಳ, ಅಂಕಿತ ಮತ್ತು ಪ್ರಮೇಯಗಳ ಮೂಲಕ ವರ್ಗೀಕರಿಸಲಾದ ರಚನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    keyFeatures: "ಪ್ರಮುಖ ಲಕ್ಷಣಗಳು",
    structuredPath: "ಆಧ್ಯಾತ್ಮಿಕ ಜ್ಞಾನದ ಕಡೆಗೆ ಒಂದು ಸಂಘಟಿತ ಹಾದಿ",
    pathDesc: "ಕೋಶವು ಭಕ್ತಿ ಅಭ್ಯಾಸ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಸಂಶೋಧನೆ ಎರಡನ್ನೂ ಸುಲಭಗೊಳಿಸಲು ಸಂಘಟಿಸಲ್ಪಟ್ಟಿದೆ.",
    historicalAuthenticity: "ಐತಿಹಾಸಿಕ ಅಧಿಕೃತತೆ",
    historicalDesc: "ಹರಿದಾಸರ ನಿಖರವಾದ ವಂಶಾವಳಿ, ಕಾಲಾವಧಿ ಮತ್ತು ಜೀವನ ಚರಿತ್ರೆಯ ವಿವರಗಳನ್ನು ಒದಗಿಸಲು ಪ್ರತಿ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಸಾಂಪ್ರದಾಯಿಕ ದಾಖಲೆಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    musicalHeritage: "ಸಂಗೀತ ಪರಂಪರೆ",
    musicalHeritageDesc: "ಕರ್ನಾಟಕ ಸಂಗೀತದ ಪಿತಾಮಹ ಪುರಂದರದಾಸರು ಮತ್ತು ಇತರ ದಿಗ್ಗಜರ ಕೃತಿಗಳ ಮೂಲಕ ಸಂಗೀತದ ಅಡಿಪಾಯವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    universalAccess: "ಸಾರ್ವತ್ರಿಕ ಪ್ರವೇಶ",
    universalAccessDesc: "ಆಧುನಿಕ ಜಿಜ್ಞಾಸುಗಳು ಮತ್ತು ಭಕ್ತರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ, ಪ್ರಾಚೀನ ಹಸ್ತಪ್ರತಿ ಸಂಪ್ರದಾಯಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ಅನುಕೂಲತೆಯ ನಡುವಿನ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.",
    haridasaruTitle: "ಹರಿದಾಸರು",
    saintsSoil: "ನಾಡಿನ ಸಂತರ",
    saintsSoilDesc: "ಪ್ರೀತಿ ಮತ್ತು ಶರಣಾಗತಿಯ ಸಂದೇಶವನ್ನು ಹರಡುತ್ತಾ ನಾಡಿನ ಉದ್ದಗಲಕ್ಕೂ ಸಂಚರಿಸಿದ ಭಕ್ತಿ ಸುಧಾರಕರನ್ನು ಭೇಟಿ ಮಾಡಿ.",
    exploreAllHaridasaru: "ಎಲ್ಲಾ ಹರಿದಾಸರನ್ನು ಅನ್ವೇಷಿಸಿ",
    devotionalContext: "ಭಕ್ತಿ ಹಿನ್ನೆಲೆ",
    exploreByDeity: "ದೇವತೆಗಳ ಮೂಲಕ ಹುಡುಕಿ",
    deityDesc: "ಹರಿದಾಸರ ರಚನೆಗಳು ಪ್ರಧಾನವಾಗಿ ಪಂಢರಪುರದ ಶ್ರೀ ವಿಠ್ಠಲ ಮತ್ತು ಭಗವಾನ್ ವಿಷ್ಣುವಿನ ವಿವಿಧ ರೂಪಗಳನ್ನು ಉದ್ದೇಶಿಸಿವೆ.",
    dailyWisdom: "ದೈನಂದಿನ ಜ್ಞಾನ",
    dailyWisdomDesc: "ಹರಿದಾಸರ ನಿತ್ಯದ ಜ್ಞಾನ, ಭಕ್ತಿ ಚಿಂತನೆ ಮತ್ತು ಸ್ಪೂರ್ತಿದಾಯಕ ರಚನೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ದಿನವನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
    wisdomQuote: "ಜ್ಞಾನದ ಮಾತು",
    reflectionTitle: "ಇಂದಿನ ಚಿಂತನೆ",
    dailySpotlight: "ಇಂದಿನ ಹರಿದಾಸ",
    practiceOfTheDay: "ದೈನಂದಿನ ಭಕ್ತಿ ಸಾಧನೆ",
    readFullComposition: "ಪೂರ್ಣ ರಚನೆಯನ್ನು ಓದಿ",
    startingPoint: "ಆರಂಭಿಕ ಹಂತ",
    journeyKeertana: "ಒಂದೇ ಕೀರ್ತನೆಯೊಂದಿಗೆ ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    journeyDesc: "ಪ್ರತಿ ರಚನೆಯು ಹರಿದಾಸರ ಅಗಾಧ ಆಧ್ಯಾತ್ಮಿಕ ಜಗತ್ತಿಗೆ ಒಂದು ಬಾಗಿಲು. ಯಾವುದಾದರೂ ಒಂದು ಕೃತಿಯೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ಅದರ ಆಳವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    modernSeeker: "ಆಧುನಿಕ ಜಿಜ್ಞಾಸುಗಳಿಗೆ ಮಾರ್ಗದರ್ಶಿ",
    modernSeekerDesc: "ನೀವು ಈ ಪರಂಪರೆಗೆ ಹೊಸಬರಾಗಿದ್ದರೆ, ಕರ್ನಾಟಕ ಸಂಗೀತದ ಪಿತಾಮಹ ಎಂದು ಕರೆಯಲ್ಪಡುವ ಶ್ರೀ ಪುರಂದರದಾಸರ ಜೀವನದಿಂದ ಪ್ರಾರಂಭಿಸಲು ನಾವು ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ.",
    browseArchive: "ಭಂಡಾರವನ್ನು ಅನ್ವೇಷಿಸಿ",
    learnHistory: "ಇತಿಹಾಸವನ್ನು ತಿಳಿಯಿರಿ",
    insideArchive: "ಭಂಡಾರದ ಒಳಗೆ",
    biographiesCount: "ಶತಮಾನಗಳಾದ್ಯಂತ ೧೫೦+ ಹರಿದಾಸರ ಜೀವನ ಚರಿತ್ರೆಗಳು",
    authenticLyrics: "ಲಿಪ್ಯಂತರದೊಂದಿಗೆ ಅಧಿಕೃತ ಕನ್ನಡ ಸಾಹಿತ್ಯ",
    philosophicalMeanings: "ಆಳವಾದ ತಾತ್ವಿಕ ಅರ್ಥಗಳು ಮತ್ತು ಇಂಗ್ಲಿಷ್ ಅನುವಾದಗಳು",
    categorization: "ರಾಗ, ತಾಳ ಮತ್ತು ಅಂಕಿತ ನಾಮಗಳ ಮೂಲಕ ವರ್ಗೀಕರಣ",
    academicDevotional: "ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಭಕ್ತಿ ಅಧ್ಯಯನ ಎರಡಕ್ಕೂ ಪೂರಕವಾಗಿದೆ",

    // Hero (Kannada)
    heroEyebrow: "ಹರಿದಾಸ ಕೋಶ",
    heroTitle: "ಹರಿದಾಸ ಪರಂಪರೆಗೆ ಒಂದು ದ್ವಾರ.",
    heroDesc: "ಪರಿಶೀಲಿಸಿದ ಹರಿದಾಸರ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಅನ್ವೇಷಿಸಿ, ಕನ್ನಡ ಸಾಹಿತ್ಯ ಮತ್ತು ಅರ್ಥದೊಂದಿಗೆ ರಚನೆಗಳನ್ನು ಓದಿ ಮತ್ತು ದಾಸ ಸಾಹಿತ್ಯದ ಆಧ್ಯಾತ್ಮಿಕ ಆಳವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    quickSearch: "ತ್ವರಿತ ಹುಡುಕಾಟ",
    searchPlaceholder: "ಹರಿದಾಸರು, ಹಾಡು ಅಥವಾ ದೇವತೆಗಳ ಮೂಲಕ ಹುಡುಕಿ...",
    exploreCompositions: "ರಚನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    meetHaridasaru: "ಹರಿದಾಸರನ್ನು ಭೇಟಿ ಮಾಡಿ",
    haridasaruDocumented: "ದಾಖಲಾದ ಹರಿದಾಸರು",
    compositionsCatalogued: "ದಾಖಲಾದ ರಚನೆಗಳು",
    languagesSupported: "ಬೆಂಬಲಿತ ಭಾಷೆಗಳು",
    howToUse: "ಈ ಕೋಶವನ್ನು ಬಳಸುವುದು ಹೇಗೆ",
    journeyStart: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    learnStep: "ಕಲಿಯಿರಿ",
    learnStepDesc: "ಹರಿದಾಸರ ಜೀವನ ಚರಿತ್ರೆ ಮತ್ತು ವಂಶಾವಳಿಯನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ.",
    readStep: "ಓದಿ",
    readStepDesc: "ಸಾಹಿತ್ಯ, ಲಿಪ್ಯಂತರ ಮತ್ತು ಅರ್ಥಗಳು ಒಂದೇ ಕಡೆ.",
    searchStep: "ಹುಡುಕಿ",
    searchStepDesc: "ಹರಿದಾಸರು, ದೇವತೆ ಅಥವಾ ಹಾಡಿನ ಸಾಲಿನ ಮೂಲಕ ಹುಡುಕಿ.",
    forNewcomers: "ಹೊಸಬರಿಗಾಗಿ",
    forNewcomersDesc: "ಪ್ರೊಫೈಲ್‌ನಿಂದ ಪ್ರಾರಂಭಿಸಿ, ನಂತರ ರಚನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    forScholars: "ವಿದ್ವಾಂಸರಿಗಾಗಿ",
    forScholarsDesc: "ಆಳವಾದ ಸಂಶೋಧನೆಗಾಗಿ ಹುಡುಕಾಟ ಮತ್ತು ವಿಷಯಗಳನ್ನು ಬಳಸಿ.",

    // About Page (Kannada)
    ourVision: "ನಮ್ಮ ದೃಷ್ಟಿಕೋನ",
    visionDesc: "ಪ್ರಾಚೀನ ಹಸ್ತಪ್ರತಿ ಸಂಪ್ರದಾಯಗಳು ಮತ್ತು ಆಧುನಿಕ ಜಿಜ್ಞಾಸುಗಳ ನಡುವಿನ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡುವ ಸಮಗ್ರ, ಸುಲಭವಾಗಿ ಪ್ರವೇಶಿಸಬಹುದಾದ ಮತ್ತು ವಿದ್ವತ್ಪೂರ್ಣವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಡಿಜಿಟಲ್ ಭಂಡಾರವನ್ನು ರಚಿಸುವುದು.",
    whyWeExist: "ನಾವು ಏಕೆ ಇದ್ದೇವೆ",
    whyWeExistDesc: "ದಾಸ ಸಾಹಿತ್ಯವು ಕೇವಲ ಸಾಹಿತ್ಯವಲ್ಲ; ಇದು ಶತಮಾನಗಳಿಂದ ಸಮುದಾಯಗಳನ್ನು ಸುಸ್ಥಿರಗೊಳಿಸಿದ ಒಂದು ಆಳವಾದ ಆಧ್ಯಾತ್ಮಿಕ, ಸಂಗೀತಮಯ ಮತ್ತು ತಾತ್ವಿಕ ಪರಂಪರೆಯಾಗಿದೆ. ಈ ಜ್ಞಾನವು ಜೀವಂತವಾಗಿರುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಾವು ಪ್ರಯತ್ನಿಸುತ್ತಿದ್ದೇವೆ.",
    digitalArchiving: "ಡಿಜಿಟಲ್ ಆರ್ಕೈವಿಂಗ್",
    digitalArchivingDesc: "ದುರ್ಲಭ ಹಸ್ತಪ್ರತಿಗಳನ್ನು ಮತ್ತು ವಿವಿಧ ಆವೃತ್ತಿಗಳನ್ನು ಒಂದುಗೂಡಿಸಿ, ಸುಲಭವಾಗಿ ಹುಡುಕಬಹುದಾದ ಮತ್ತು ಸಂಘಟಿತ ಡೇಟಾಬೇಸ್ ಆಗಿ ಪರಿವರ್ತಿಸುವುದು.",
    communityEngagement: "ಸಮುದಾಯದ ಪಾಲ್ಗೊಳ್ಳುವಿಕೆ",
    communityEngagementDesc: "ವಿದ್ವಾಂಸರು, ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ಭಕ್ತರು ಕಲಿಯಲು, ಚರ್ಚಿಸಲು ಮತ್ತು ಸಾಮೂಹಿಕ ತಿಳುವಳಿಕೆಗೆ ಕೊಡುಗೆ ನೀಡಲು ಉತ್ತೇಜಿಸುವ ವೇದಿಕೆಯನ್ನು ನಿರ್ಮಿಸುವುದು.",
    aboutEyebrow: "ನಮ್ಮ ಉಪಕ್ರಮ",
    aboutTitle: "ಹರಿದಾಸ ಕೋಶ ಯೋಜನೆ",
    aboutLead: "ಹರಿದಾಸರ ಸಂಪೂರ್ಣ ಕೃತಿಗಳನ್ನು ಡಿಜಿಟಲೀಕರಣಗೊಳಿಸಲು, ಅನುವಾದಿಸಲು ಮತ್ತು ಮುಂದಿನ ಪೀಳಿಗೆಗೆ ಸಂರಕ್ಷಿಸಲು ಒಂದು ಸಹಕಾರಿ ಪ್ರಯತ್ನ.",
    historyTitle: "೧೩ನೇ ಶತಮಾನದಲ್ಲಿ ಬೇರೂರಿದೆ",
    historyDesc1: "ಹರಿದಾಸ ಸಾಹಿತ್ಯವು ಉನ್ನತ ತತ್ವಶಾಸ್ತ್ರ ಮತ್ತು ಸರಳ ಕಾವ್ಯದ ವಿಶಿಷ್ಟ ಸಮ್ಮಿಲನವನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ. ಶ್ರೀ ನರಹರಿ ತೀರ್ಥರು ಮತ್ತು ಶ್ರೀ ಶ್ರೀಪಾದರಾಜರಿಂದ ಪ್ರಾರಂಭವಾದ ಈ ಚಳುವಳಿಯು ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಕಾಲದಲ್ಲಿ ಉತ್ತುಂಗಕ್ಕೇರಿತು.",
    historyDesc2: "ಮರೆಯಾಗುತ್ತಿರುವ ಹಸ್ತಪ್ರತಿಗಳಿಂದ ಈ ಅಗಾಧವಾದ ಸಾಹಿತ್ಯವನ್ನು ಹೊರತಂದು ಆಧುನಿಕ ಪ್ರೇಕ್ಷಕರಿಗೆ ಸುಲಭವಾಗಿ ಸಿಗುವಂತೆ ಮಾಡುವುದು ನಮ್ಮ ಯೋಜನೆಯ ಗುರಿಯಾಗಿದೆ.",
    methodologyTitle: "ನಮ್ಮ ಕಾರ್ಯವೈಖರಿ",
    methodologyDesc: "ರಚನೆಗಳ ಪವಿತ್ರತೆ ಮತ್ತು ನಿಖರತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ನಾವು ಕಟ್ಟುನಿಟ್ಟಾದ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಅನುಸರಿಸುತ್ತೇವೆ.",
    archivalIntegrity: "ಆರ್ಕೈವಲ್ ಸಮಗ್ರತೆ",
    archivalIntegrityDesc: "ಪ್ರತಿ ರಚನೆಯ ಸಾಹಿತ್ಯ ಮತ್ತು ಕರ್ತೃತ್ವವನ್ನು ಪರಿಶೀಲಿಸಲು ನಾವು ಮೂಲ ಆಕರಗಳನ್ನು ಬಳಸುತ್ತೇವೆ.",
    scholarlyVetting: "ವಿದ್ವತ್ಪೂರ್ಣ ಪರಿಶೀಲನೆ",
    scholarlyVettingDesc: "ನಮ್ಮ ಅನುವಾದಗಳು ಮತ್ತು ಅರ್ಥಗಳನ್ನು ವಿದ್ವಾಂಸರು ಪರಿಶೀಲಿಸುತ್ತಾರೆ.",
    digitalPreservation: "ಡಿಜಿಟಲ್ ಸಂರಕ್ಷಣೆ",
    digitalPreservationDesc: "ಮಾಹಿತಿಯನ್ನು ಭವಿಷ್ಯದ ದೃಷ್ಟಿಯಿಂದ ಸಂಘಟಿಸಲಾಗಿದೆ ಮತ್ತು ಸಂಶೋಧಕರಿಗೆ ಲಭ್ಯವಾಗುವಂತೆ ಮಾಡಲಾಗಿದೆ.",
    joinMissionTitle: "ನಮ್ಮ ಮಿಷನ್ ಸೇರಿ",
    joinMissionDesc: "ನೀವು ವಿದ್ವಾಂಸರಾಗಿರಲಿ, ಗಾಯಕರಾಗಿರಲಿ ಅಥವಾ ಭಕ್ತರಾಗಿರಲಿ, ಈ ಬೆಳೆಯುತ್ತಿರುವ ಡಿಜಿಟಲ್ ಲೈಬ್ರರಿಗೆ ಕೊಡುಗೆ ನೀಡಲು ಹಲವು ಮಾರ್ಗಗಳಿವೆ.",
    contributeBtn: "ಈಗಲೇ ಕೊಡುಗೆ ನೀಡಿ",
    contactBtn: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    composers: "ಹರಿದಾಸರು",
    compositions: "ರಚನೆಗಳು",
    contributors: "ಕೊಡುಗೆದಾರರು",
    yearsOfHistory: "ವರ್ಷಗಳ ಇತಿಹಾಸ",

    // Featured (Kannada)
    featuredEyebrow: "ನಿಮಗಾಗಿ ಆರಿಸಿದ್ದು",
    featuredTitle: "ಪ್ರಮುಖ ರಚನೆಗಳು",
    featuredDesc: "ತಲೆಮಾರುಗಳಿಂದ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತಿರುವ ಪ್ರೀತಿಯ ಭಕ್ತಿ ರಚನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    viewEntireCollection: "ಸಂಪೂರ್ಣ ಸಂಗ್ರಹವನ್ನು ನೋಡಿ",

    // Compositions Page (Kannada)
    compositionsHeading: "ಹರಿದಾಸ ರಚನೆಗಳು",
    compositionsSubtitle: "ದ್ವೈತ ಸಂಪ್ರದಾಯದ ಭಕ್ತಿ ರಚನೆಗಳ ಅತಿದೊಡ್ಡ ಹುಡುಕಬಹುದಾದ ಸಂಗ್ರಹವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    statsCompositions: "ರಚನೆಗಳು",
    statsHaridasas: "ಹರಿದಾಸರು",
    statsRagas: "ರಾಗಗಳು",
    statsAnkitas: "ಅಂಕಿತಗಳು",
    popularSearches: "ಜನಪ್ರಿಯ ಹುಡುಕಾಟಗಳು",
    exploreByHaridasa: "ಹರಿದಾಸರ ಮೂಲಕ ಅನ್ವೇಷಿಸಿ",
    featuredCompositionOfTheDay: "ಇಂದಿನ ಪ್ರಮುಖ ರಚನೆ",
    readComposition: "ರಚನೆಯನ್ನು ಓದಿ",
    quickFilters: "ತ್ವರಿತ ಫಿಲ್ಟರ್‌ಗಳು",
    all: "ಎಲ್ಲಾ",
    moreFilters: "ಹೆಚ್ಚಿನ ಫಿಲ್ಟರ್‌ಗಳು",
    grid: "ಗ್ರಿಡ್",
    list: "ಪಟ್ಟಿ",
    read: "ಓದಿ",

    aiMeaningfulWelcome: "ನಮಸ್ಕಾರ. ಹರಿದಾಸ ಕೋಶಕ್ಕೆ ಸ್ವಾಗತ. ನಾನು ನಿಮ್ಮ AI ಸಹಾಯಕ, ದಾಸ ಸಾಹಿತ್ಯದ ದೈವಿಕ ಕಾವ್ಯ ಮತ್ತು ತತ್ವಶಾಸ್ತ್ರವನ್ನು ಅನ್ವೇಷಿಸಲು ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ. ಹರಿದಾಸರ ಜೀವನ, ಕೀರ್ತನೆಯ ಅರ್ಥ ಅಥವಾ ಮಧ್ವ ತತ್ವಶಾಸ್ತ್ರದ ಬಗ್ಗೆ ನನ್ನನ್ನು ಕೇಳಿ.",
    aiErrorMessage: "ಕ್ಷಮಿಸಿ, ನನ್ನ ಜ್ಞಾನ ಭಂಡಾರವನ್ನು ಸಂಪರ್ಕಿಸಲು ತೊಂದರೆಯಾಗುತ್ತಿದೆ.",
    enterSearchQuery: "ರಚನೆಗಳು ಮತ್ತು ಹರಿದಾಸರನ್ನು ಹುಡುಕಲು ಪದವನ್ನು ನಮೂದಿಸಿ.",
    noResultsFound: "ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ:",
    tryDifferentSearch: "ಬೇರೆ ಪದ ಬಳಸಿ ಹುಡುಕಿ.",

    // UI & Common (Kannada)
    noDailyWisdomAvailable: "ಯಾವುದೇ ದೈನಂದಿನ ಜ್ಞಾನ ಲಭ್ಯವಿಲ್ಲ.",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    haridasa: "ಹರಿದಾಸ",
    historical: "ಐತಿಹಾಸಿಕ",
    exploreProfile: "ಪ್ರೊಫೈಲ್ ನೋಡಿ",
    open: "ಓದಿ",
    defaultBio: "ಭಕ್ತಿ ಮತ್ತು ಜ್ಞಾನದ ಮೂಲಕ ಸನ್ಮಾರ್ಗವನ್ನು ತೋರಿದ ಹರಿದಾಸರು.",
    archivalEntry: "ದಾಖಲೆ",
    primaryRecord: "ಮುಖ್ಯ ದಾಖಲೆ",
    master: "ರಚನೆಕಾರರು",
    subject: "ದೇವತೆ",
    vittala: "ವಿಠ್ಠಲ",
    krishna: "ಕೃಷ್ಣ",
    rama: "ರಾಮ",
    lakshmi: "ಲಕ್ಷ್ಮಿ",
    narasimha: "ನರಸಿಂಹ",
    hanuman: "ಹನುಮಂತ",
    srinivasa: "ಶ್ರೀನಿವಾಸ",
    shiva: "ಶಿವ",
    "Purandara Dasa": "ಪುರಂದರ ದಾಸ",
    "Kanaka Dasa": "ಕನಕ ದಾಸ",
    "Vittala": "ವಿಠ್ಠಲ",
    "Krishna": "ಕೃಷ್ಣ",
    "Ugabhoga": "ಉಗಾಭೋಗ",
    filters: "ಫಿಲ್ಟರ್‌ಗಳು",
    clearAll: "ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ",
    composerLabel: "ಹರಿದಾಸರು",
    deityLabel: "ದೇವತೆ",
    ankitaLabel: "ಅಂಕಿತ",
    ragaLabel: "ರಾಗ",
    talaLabel: "ತಾಳ",
    tagLabel: "ಟ್ಯಾಗ್‌ಗಳು",
    allComposers: "ಎಲ್ಲಾ ಹರಿದಾಸರು",
    allDeities: "ಎಲ್ಲಾ ದೇವತೆಗಳು",
    allAnkitas: "ಎಲ್ಲಾ ಅಂಕಿತಗಳು",
    allRagas: "ಎಲ್ಲಾ ರಾಗಗಳು",
    allTalas: "ಎಲ್ಲಾ ತಾಳಗಳು",
    allTags: "ಎಲ್ಲಾ ಟ್ಯಾಗ್‌ಗಳು",
    kannadaLyrics: "ಕನ್ನಡ ಸಾಹಿತ್ಯ",
    englishTranslation: "ಇಂಗ್ಲಿಷ್ ಅನುವಾದ",
    audioRecordings: "ಧ್ವನಿ ಸುರುಳಿಗಳು",
    play: "ಕೇಳಿ",
    prototypeWarning: "ಪ್ರಾಥಮಿಕ ಪ್ರೋಟೋಟೈಪ್ - ಕಾರ್ಯಗಳು ಸೀಮಿತವಾಗಿರಬಹುದು.",
    askAiPrototypeWarning: "ಸೀಮಿತ ಅನುಷ್ಠಾನದಿಂದಾಗಿ AI ನಿರೀಕ್ಷೆಯಂತೆ ಕಾರ್ಯನಿರ್ವಹಿಸದಿರಬಹುದು."
    }
    };

const LanguageContext = createContext({
  lang: 'EN',
  setLang: (lang: string) => {},
  t: (key: string) => ''
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState('EN');
  
  const t = useMemo(() => (key: string) => {
    return (translations as any)[lang]?.[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
