'use client';
import React, { createContext, useContext, useState, useMemo, useEffect } from 'react';

const translations = {
  EN: {
    aboutEyebrow: "Our Initiative",
    aboutLead: "A collaborative effort to digitize, translate, and preserve the complete works of the Haridasaru for future generations.",
    aboutTitle: "The Haridasa Kosha Project",
    aiErrorMessage: "Sorry, I am having trouble connecting to my knowledge base.",
    aiMeaningfulWelcome: "Namaste. Welcome to The Haridasa Kosha. I am your AI companion, here to help you discover the divine poetry and profound philosophy of the Dasa Sahitya. Ask me about the lives of the Haridasaru, the meaning of a Keertana, or the core tenets of Dvaita Vedanta.",
    ankita: "Ankita",
    archivalEntry: "Archival Entry",
    askAiPrototypeWarning: "AI may not work as expected due to limited implementation.",
    autoFlowTimeline: "Auto-flowing through eternity. Hover a card to pause.",
    brand: "The Haridasa Kosha",
    browseArchive: "Browse Archive",
    clearAll: "Clear All",
    communityEngagement: "Community Engagement",
    communityEngagementDesc: "Building a platform that invites scholars, students, and devotees to learn, discuss, and contribute to the collective understanding.",
    composer: "Composer",
    composerLabel: "Composer",
    deityLabel: "Deity",
    ankitaLabel: "Ankita",
    Unknown: "Unknown",
    composersPageDesc: "Meet the great saints who shared God's love through simple songs and stories.",
    composersPageTitle: "The Haridasa Parampara",
    compositions: "Compositions",
    compositionsHeading: "Haridasa Compositions",
    compositionsSubtitle: "Explore the largest searchable collection of devotional compositions from the Dvaita tradition.",
    contactBtn: "Contact Us",
    contributeBtn: "Contribute Now",
    contributeSubtitle: "Join our mission to preserve, digitize, and share the divine wisdom of the Haridasaru.",
    contributeTitle: "Contribute to The Haridasa Kosha",
    dailyWisdom: "Daily Wisdom",
    dailyWisdomDesc: "A fresh devotional reflection for today from the archive.",
    defaultBio: "A revered Haridasa whose compositions continue to guide spiritual seekers.",
    deity: "Deity",
    digitalArchiving: "Digital Archiving",
    digitalArchivingDesc: "Converting rare manuscripts and disparate editions into a unified, searchable, and structured database.",
    digitalPreservation: "Digital Preservation",
    digitalPreservationDesc: "Data is structured to be future-proof and accessible via open APIs for researchers worldwide.",
    dwAskAI: "Ask AI",
    dwDasarapada: "Dasarapada",
    dwHaridasa: "Haridasa",
    dwJourney: "Journey",
    dwListen: "Listen",
    dwRaga: "Raga",
    dwReadMeaning: "Read Meaning",
    dwThought: "Thought",
    englishTranslation: "English Translation",
    exploreAllHaridasaru: "Explore All Haridasaru",
    exploreBtn: "Explore",
    exploreCompositions: "Explore Compositions",
    exploreProfile: "Explore profile",
    featuredDesc: "Explore beloved devotional melodies that have guided seekers for generations.",
    featuredEyebrow: "Handpicked for you",
    featuredTitle: "Featured Compositions",
    filters: "Filters",
    getStartedBtn: "Get Started",
    haridasa: "Haridasa",
    heroDesc: "Explore verified Haridasa profiles, read compositions with Kannada lyrics and meaning, and discover the spiritual depth of the Dasa Sahitya.",
    heroSub: "A gateway to the Haridasa tradition.",
    heroTitle: "A gateway to the Haridasa tradition.",
    historical: "Historical",
    insideArchive: "Inside the Archive",
    joinMissionDesc: "Whether you are a scholar, a singer, or a devotee, there are many ways to contribute to this growing digital library.",
    joinMissionTitle: "Join Our Mission",
    kannadaLyrics: "Kannada Lyrics",
    learnHistory: "Learn the History",
    limit: "Limit",
    livingTradition: "A Living Tradition",
    livingTraditionDesc: "Founded on the principles of Dvaita philosophy, the Haridasa movement democratized spiritual knowledge through song. From the foundational works of Sri Narahari Tirtha to the prolific legacy of Purandara Dasa, this platform serves as a bridge for the modern world to access this profound wisdom.",
    loading: "Loading...",
    methodologyDesc: "We maintain a rigorous process for archival and presentation to ensure that the sanctity and accuracy of the compositions are preserved.",
    methodologyTitle: "Our Methodology",
    modernSeeker: "A Guide for the Modern Seeker",
    modernSeekerDesc: "If you are new to the tradition, we recommend starting with the life of Sri Purandara Dasa, often called the Father of Carnatic Music. From there, you can explore themes like surrender (Sharanagati), social reform, and philosophical enquiry (Prameya).",
    navAbout: "About",
    about: "About",
    navLibrary: "Library",
    navComposers: "Haridasaru",
    navConnections: "Connections",
    navParampara: "Parampara",
    madhwacharyaBio: "Sri Madhvacharya (1238–1317) was the founder of the Dvaita school of Vedanta. He is the original source of inspiration for the Haridasa movement, providing the philosophical foundation of Bhakti towards Lord Krishna.",
    paramparaSubtitle: "Explore how the Haridasa movement grew over 800 years like a beautiful river of devotion.",
    eraFoundational: "Foundational Era",
    eraGolden: "Golden Era",
    eraExpansion: "Expansion Era",
    eraModern: "Modern Era",
    eraFoundationalDesc: "The seeds were sown by Sri Madhvacharya and the first Haridasa, Sri Narahari Tirtha.",
    eraGoldenDesc: "The movement flourished under Sri Purandara Dasa and Sri Kanaka Dasa in Vijayanagara.",
    eraExpansionDesc: "Sri Vijaya Dasa and Jagannatha Dasa spread the message to every household.",
    eraModernDesc: "The tradition continues to inspire seekers through digital preservation and study.",
    timelineStart: "13th Century",
    timelineEnd: "Present Day",
    kidFriendlyMessage: "Hey kids! Follow the lotus path to see how these great saints sang their way to God!",
    name: "English",
    carouselTitle1: "Extensive Digital Library",
    carouselDesc1: "Access hundreds of authentic Devaranamas composed by the legendary Haridasas.",
    carouselTitle2: "In-Depth English Translations",
    carouselDesc2: "Understand the profound meanings with word-by-word transliterations and contextual translations.",
    carouselTitle3: "Haridasa Biographies",
    carouselDesc3: "Explore the rich, detailed histories and spiritual journeys of the great saints.",
    carouselTitle4: "Musical Heritage",
    carouselDesc4: "Discover traditional Raga and Tala metadata, perfect for musicians and researchers.",
    navHome: "Home",
    navAskAI: "Ask AI",
    navComposers: "Haridasaru",
    navDailyWisdom: "Daily Wisdom",
    navLibrary: "Library",
    offset: "Offset",
    open: "Open",
    ourVision: "Our Vision",
    popularSearches: "Popular Searches",
    practiceOfTheDay: "Practice of the Day",
    proofreading: "Proofreading",
    proofreadingDesc: "Review lyrics and transcriptions to ensure textual accuracy.",
    prototypeWarning: "Early prototype - functionalities may be limited.",
    q: "Q",
    raga: "Raga",
    ragaLabel: "Raga",
    read: "Read",
    readFullComposition: "Read Full Composition",
    reflectionTitle: "Reflection",
    search: "Search",
    searchComposers: "Search composers...",
    "Ranga Vittala": "Ranga Vittala",
    "Purandara Vittala": "Purandara Vittala",
    "Vijaya Vittala": "Vijaya Vittala",
    "Jagannatha Vittala": "Jagannatha Vittala",
    "Gopala Vittala": "Gopala Vittala",
    "Venugopala": "Venugopala",
    "Kaginele Adikeshava": "Kaginele Adikeshava",
    "Bhimesha Krishna": "Bhimesha Krishna",
    "Hayavadana": "Hayavadana",
    "Prasanna Venkata": "Prasanna Venkata",
    "mahipati": "Mahipati",
    statsAnkitas: "Ankitas",
    statsCompositions: "Compositions",
    statsHaridasas: "Haridasas",
    statsRagas: "Ragas",
    tag: "Tag",
    tailwindcss: "Tailwind CSS",
    globalAccess: "Global Access",
    global: "Global",
    tala: "Tala",
    talaLabel: "Tala",
    "Ahudhadharu adhudhennni": "Ahudhadharu Ahudenni",
    "Arigaadharu purva": "Arigaadharu Purva",
    "Aritu nadeyalu beku narakayavettida mele": "Aritu Nadeyalu Beku",
    "Aru hitavaru endu nambabeda": "Aru Hitavaru Endu Nambabeda",
    "Ava siriyali ninu enna marete": "Ava Siriyali Ninu Enna Marete",
    "Badukidenu badukidenu bhava enage hingitu": "Badukidenu Badukidenu",
    "Bagilanu teredu seveyanu kodo hariye": "Bagilanu Teredu",
    "Baro krushnayya krushnayya": "Baro Krushnayya",
    "Bajare Hanumantam": "Bajare Hanumantam",
    "Bandevaya govinda setti": "Bandevaya Govinda Setti",
    "Bandhu trijagake sri hariyallade mikka": "Bandhu Trijagake",
    "Beda beda elele": "Beda Beda Elele",
    tblActions: "Actions",
    tblAnkita: "Ankita nama",
    tblName: "Composer Name",
    tblPeriod: "Year",
    technicalSupport: "Technical Support",
    technicalSupportDesc: "Contribute your technical expertise to improve our archive.",
    thinking: "Thinking...",
    transcription: "Transcription",
    transcriptionDesc: "Help transcribe palm-leaf manuscripts into digital formats.",
    translation: "Translation",
    translationDesc: "Translate devotional meanings into English and other languages.",
    view: "View",
    viewEntireCollection: "View Entire Collection",
    viewProfile: "View Profile",
    yes: "Yes",
    no: "No",
    visionDesc: "To create a comprehensive, accessible, and scholarly-vetted digital repository that bridges the gap between ancient manuscript traditions and modern seekers.",
    whyWeExist: "Why We Exist",
    whyWeExistDesc: "The Dasa Sahitya is not just literature; it is a profound spiritual, musical, and philosophical heritage that has sustained communities for centuries. We exist to ensure this wisdom remains vibrant.",
    wisdomQuote: "Wisdom Quote",
    yearsOfHistory: "Years of History",
    paramparaTitle: "Parampara",
    paramparaDesc: "Explore the continuous, 800-year-old river of devotion starting from Sri Madhvacharya and Narahari Tirtha.",
    archivalIntegrity: "Archival Integrity",
    archivalIntegrityDesc: "Ensuring the sanctity and accuracy of the compositions.",
    scholarlyVetting: "Scholarly Vetting",
    scholarlyVettingDesc: "Scholarly research and vetting of compositions.",

    // Missing Keys
    Compositions: "Compositions",
    missionEyebrow: "The Mission",
    missionTitle: "Preserving the Voice of Devotion",
    missionDesc: "The Haridasa Kosha is a digital repository dedicated to the preservation and study of Dasa Sahitya—the devotional literature of the Haridasaru of Karnataka.",
    keyFeatures: "Key Features",
    structuredPath: "A Structured Path to Spiritual Knowledge",
    pathDesc: "The Kosha is organized to facilitate both devotional practice and academic research, providing multiple lenses to view the Haridasa tradition.",
    haridasaruTitle: "Haridasaru",
    saintsSoil: "The Saints of the Soil",
    saintsSoilDesc: "Meet the devotional reformers who travelled the length and breadth of the land, spreading the message of love and surrender.",
    devotionalContext: "Devotional Context",
    exploreByDeity: "Explore by Deity",
    deityDesc: "The Haridasa compositions are predominantly addressed to Lord Vittala of Pandharpur and various forms of Lord Vishnu. Explore works dedicated to specific deities.",
    startingPoint: "A Starting Point",
    journeyKeertana: "Begin Your Journey with a Single Keertana",
    journeyDesc: "Every composition is a door to the profound spiritual world of the Haridasaru. Start with a random work and explore its depth.",
    "Vyasa Kuta": "Vyasa Kuta",
    "Dasa Kuta": "Dasa Kuta",
    "Udupi Krishna": "Udupi Krishna",
    "Vittala Keertana": "Vittala Keertana",
    "Haridasa Namavali": "Haridasa Namavali",
    Haridasa: "Haridasa",
    foundations: "Foundations",
    verifiedKeertanas: "Verified Keertanas",
    discoverStories: "Discover Stories",
    studyStructures: "Study Structures",
    archiveTitle: "Archive",
    archiveDesc: "Browse a comprehensive collection of verified Keertanas, Suladis, and Ugabhogas with full lyrics.",
    scholarlyTitle: "Scholarly",
    scholarlyDesc: "Access translations, word-by-word meanings, and cultural context verified by traditional scholars.",
    historicalAuthenticity: "Historical Authenticity",
    historicalDesc: "Every composition is verified against multiple palm-leaf manuscripts and rare printed editions.",
    musicalHeritage: "Musical Heritage",
    musicalHeritageDesc: "Study raga, tala, and the foundational pedagogical structures laid down by Sri Purandara Dasa.",
    universalAccess: "Universal Access",
    universalAccessDesc: "Free, searchable, and structured data made accessible for researchers, musicians, and devotees worldwide.",
    biographiesCount: "Biographies",
    authenticLyrics: "Authentic Lyrics",
    philosophicalMeanings: "Philosophical Meanings",
    categorization: "Categorization",
    academicDevotional: "Academic Devotional",
    vittala: "Vittala",
    krishna: "Krishna",
    rama: "Rama",
    lakshmi: "Lakshmi",
    narasimha: "Narasimha",
    hanuman: "Hanuman",
    srinivasa: "Srinivasa",
    shiva: "Shiva",
    Vittala: "Vittala",
    Krishna: "Krishna",
    Rama: "Rama",
    Lakshmi: "Lakshmi",
    Narasimha: "Narasimha",
    Hanuman: "Hanuman",
    Srinivasa: "Srinivasa",
    Shiva: "Shiva",
    paramparaHeading: "The Haridasa Parampara",
    paramparaLead: "A journey through the divine lineage of saints",
    madhwacharya: "Sri Madhwacharya",
    madhwacharyaru: "Sri Madhwacharyaru",
    madhwacharyaSloka: "abhramaṁ bhaṅgarahitaṁ ajaḍaṁ vimalaṁ sadā |\nānandatīrthamatulaṁ bhajē tāpatrayāpahaṁ||",
    narahariTirtha: "Sri Narahari Tirtha",
    narahariTirthaDesc: "Sri Narahari Tirtha (c. 1243 – 1333 CE) was a prominent Dvaita philosopher, statesman, and the progenitor of the Haridasa movement. He was a direct disciple of Sri Madhvacharya and served as the second pontiff of the Madhva lineage. He is considered the first Haridasa to compose devotional songs in the Kannada language, paving the way for the tradition to spread to the masses.",
    narahariTirthaSloka: "sasItAmUlarAmArchA koshe gajapateH sthitA |\nyenAnItA namastasmai shrImannR^iharibhixave||",
    sripadarajaru: "Sri Sripadarajaru",
    sripadarajaDesc: "Sri Sripadarajaru (1404–1502) was a great Haridasa and the pontiff of the Sripadaraja Matha at Mulbagal. He is considered the pioneer of the Dasa Sahitya movement in Karnataka, laying the foundation for the devotional tradition. A prolific composer, he introduced the Suladi and Ugabhoga forms of compositions, which greatly enriched the devotional music of the Dasa tradition. He was a profound scholar, a philosopher, and a direct disciple of Sri Brahmanya Tirtha, known for his deep spiritual insights and intense devotion to Lord Ranga Vittala.",
    sripadarajaSloka: "Taṁ Vandē Narasimhatīrthanilayaṁ Śrīvyāsarāṭ Pūjitaṁ |\nDhyāyantaṁ Manasā Nṛsiṁhacaraṇam Śrīpādarājaṁ Guruṁ||",
    vyasatirtha: "Sri Vyasatirtharu",
    vyasatirthaName: "Sri Vyasatirtharu",
    vyasatirthaDesc: "Sri Vyasarayaru was the disciple of Sripadarajaru. His father was Ballana Tirtha and his mother was Lakshmidevi. His birth name was Yatiraja. Sri Brahmanya Tirtha gave him sannyasa deeksha and named him Vyasatirtha. He served as the Raja Guru to six emperors of the Vijayanagara Empire, including Saluva Narasimha. By warding off the Kuhu Yoga for Krishnadevaraya, he earned royal honors. He was a profound scholar in both Sanskrit and Kannada. His ankitas include 'Krishna', 'Sri Krishna', 'Siri Krishna', and 'Muddu Krishna'. He took the Haridasa deeksha with the aim of propagating Madhva philosophy. The formation of the Dasa Koota is one of his most significant achievements. Vadiraja, Purandara, and Kanaka are the prominent figures of Dasa Koota. He lived between 1447 and 1539.",
    vyasatirthaSloka: "arthikalpitakalpō'yaṁ pratyarthigajakēsarī |\nvyāsatīrthagururbhūyādasmadiṣṭārtha siddhayē||",
    vadirajaTirthaDesc: "'Hayavadana' is the ankita (pen name) of Sri Vadiraja. A disciple of Vyasarayaru, Vadiraja was born in Huvinakere near Kundapur in Dakshina Kannada district (1480 CE). He authored texts in Sanskrit, Kannada, and Tulu. He composed Sanskrit works such as 'Rukminisha Vijaya', 'Yukti Mallika', and 'Sarasa Bharati Vilasa'. In Kannada, he authored works like 'Vaikuntha Varnane', 'Lakshmi Shobhane', 'Swapnapada', 'Kichaka Vadha', and 'Keshava Nama'. His compositions clearly reflect social concern and deep devotion. As the head of the Sodhe Mutt, one of the Ashta Mutts of Udupi, he reorganized the administrative system of the Ashta Mutts and established the 'Paryaya' system with a two-year duration for the worship of Lord Krishna.",
    vadirajaTirthaSloka: "tapō vidyā viraktyādi sadghuṇou ghākarānaham |\nvādirāja gurūn vandē hayagrīva dayāśrayan||",
    purandaraDasa: "Sri Purandara Dasa",
    purandaraDasaDesc: "Father of Carnatic music, systematized devotional pedagogy.",
    purandaraDasaSloka: "manmanōbhīṣṭa varadaṁ sarvābhīṣṭa phalapradaṁ |\npurandara guruṁ vandē dāsaśrēṣṭha dayānidhim||",
    kanakaDasa: "Sri Kanaka Dasa",
    kanakaDasaDesc: "Poet, social reformer, democratized spiritual knowledge.",
    kanakaDasaSloka: "yamāṁśasya parābhaktyā suprasannō hariḥ svayaṁ |\nyasyācāryō vyāsarāyaḥ taṁ vandē kanakābhidhaṁ||",
    vijayaDasa: "Sri Vijaya Dasa",
    vijayaDasaDesc: "Profound composer, spread the message extensively.",
    vijayaDasaSloka: "ajñāna timiracchēdaṁ buddhi sampatpradāyakam |\nvijñānaṁ vimalaṁ śāntaṁ vijayākhyaṁ guruṁ bhajē||",
    gopalaDasaSloka: "āgatādi trikālajñām āgamārtha viśāradam |\ntyāga bhōga samāyuktam bhāgaṇṇārya guruṁ bhajē||",
    gopalaDasaDesc: "Sri Gopala Dasaru (1721–1769), born as Bhaganna, was a prominent saint-composer of the Haridasa tradition. He composed extensively under the ankita 'Gopala Vittala' and was a disciple of Sri Vijaya Dasaru. He is celebrated for his profound spiritual knowledge, mystic experiences, and dedicating his life extension to Jagannatha Dasaru.",
    jagannathaDasa: "Sri Jagannatha Dasa",
    jagannathaDasaDesc: "Known for the monumental \"Harikathamrutasara\".",
    jagannathaDasaSloka: "jalāśrēṣṭhanibhākāraṁ jagadīśapadāśrayam |\njagatītalavikhyātaṁ jagannāthaguruṁ bhajē||",
    thirteenthCentury: "13th Century",
    fourteenthCentury: "14th Century",
    fifteenthCentury: "15th Century",
    purandaraDasaru: "Sri Purandara Dasaru",
    kanakaDasaru: "Sri Kanaka Dasaru",
    vijayaDasaru: "Sri Vijaya Dasaru",
    gopalaDasaru: "Sri Gopala Dasaru",
    jagannathaDasaru: "Sri Jagannatha Dasaru",
    mohanaDasaru: "Sri Mohana Dasaru",
    helavanakatteGiriyamma: "Helavanakatte Giriyamma",
    srinivasaDasaru: "Srinivasa Dasaru",
    lakshmipatiDasaru: "Lakshmipati Dasaru",
    madhwapatiDasaru: "Madhwapati Dasaru",
    venkateshaDasaru: "Venkatesha Dasaru",
    narahariDasaru: "Narahari Dasaru",
    govindaDasaru: "Govinda Dasaru",
    ugabhogaNarayanaDasaru: "Ugabhoga Narayana Dasaru",
    venugopalaDasaru: "Venugopala Dasaru",
    vishnuDasaru: "Vishnu Dasaru",
    krishnapriyaDasaru: "Krishnapriya Dasaru",
    mohanaDasaDesc: "Mohana Dasaru (1728–1751) was a prominent saint-composer of the Haridasa tradition, known for his works composed under the pen name 'Mohana Vittala'. Saved from a suicide attempt in the Tungabhadra River by the great saint Sri Vijaya Dasaru, he was raised, educated, and initiated into the Haridasa path by him.",
    mohanaDasaSloka: "mōhabhaya duḥkhādidūraṁ lōhalōṣṭha samēkṣaṇaṁ |\nmāhitāṅghri sarōjabhṛṅgaṁ mōhanārya guruṁ bhajē||",
    subbannaDasaru: "Sri Kalluru Subbanna Dasaru",
    subbannaDasaDesc: "A revered 18th-century Haridasa saint and composer from Kalluru.",
    subbannaDasaSloka: "vyāsaviṭhṭhala dāsēndraṁ jñānabhakti parāyaṇaṁ |\nvijayadāsa kṛpāpātraṁ namāmi kallūru haridāsam||",
    raghavendraDasaru: "Sri Raghavendra Tirtharu",
    raghavendraDasaDesc: "A revered 17th-century saint, philosopher, and scholar in the Dvaita tradition who entered Brindavana alive in Mantralayam.",
    raghavendraDasaSloka: "pūjyāya rāghavēndrāya satyadharma ratāyaca |\nbhajatāṁ kalpavṛkṣāya namatāṁ kāmadhēnavē||",
    satyabodhaDasaru: "Sri Satyabodha Tirtharu",
    satyabodhaDasaDesc: "A highly venerated 18th-century guru and saint who served as the pontiff of the Uttaradi Matha.",
    satyabodhaDasaSloka: "naivēdyagaviṣaṁ rāmē vīkṣya tadbhuktibhāk guruḥ |\nyō'darśayadraviṁ rātrau satyabōdhō'stu mē mudē||",
    harapanahalliBhimavva: "Harapanahalli Bhimavva",
    harapanahalliBhimavvaDesc: "A prolific 19th-century female saint-composer who composed under the ankita 'Bhimesha Krishna'.",
    harapanahalliBhimavvaSloka: "nāradādāpta sadbōdhāṁ sādhvī sāhitya kāriṇīṁ |\nbhīmēśa kṛṣṇa niratāṁ vandē bhīmavva mātaraṁ||",
    mahipatiDasaru: "Mahipati Dasaru",
    mahipatiDasaDesc: "A revered 17th-century Haridasa saint-composer from Kakhandaki, known for his mystical compositions in Kannada, Marathi, Urdu and Sanskrit.",
    mahipatiDasaSloka: "jagadguruṁ kṛpā sindhuṁ śaraṇāgata vatsalam |\nbhaktamānasa sañcāraṁ mahipati guruṁ bhajē||",
    praneshaDasaru: "Sri Pranesha Dasaru",
    praneshaDasaDesc: "A prominent 18th-century Haridasa saint-composer, disciple of Jagannatha Dasaru, who composed under the pen name 'Pranesha Vittala'.",
    praneshaDasaSloka: "prāṇapati padadvandva paṅkajāsaktamānasaṁ |\nśamādiguṇa saṁyuktaṁ śrīprāṇēśa guruṁ bhajē||",
    prasannaVenkataDasaru: "Prasanna Venkata Dasaru",
    prasannaVenkataDasaDesc: "A major 18th-century saint-composer from Bagalkot, known for his deep devotional poetry under the pen name 'Prasanna Venkata'.",
    prasannaVenkataDasaSloka: "śrī śātprāpta suvijñānam śrīśaika nirataṁ sadā |\nprasanna vēṅkaṭāryōmē bhūyāt sarvārtha siddhayē||",
    srinivasaDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    lakshmipatiDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    madhwapatiDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    venkateshaDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    narahariDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    govindaDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    ugabhogaNarayanaDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    venugopalaDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    vishnuDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    krishnapriyaDasaDesc: "A revered saint-composer of the Haridasa tradition.",
    vadirajaTirtharu: "Sri Vadiraja Tirtharu",
    narahariTirtharu: "Sri Narahari Tirtharu",
    reveredHaridasa: "A revered Haridasa.",
    "1238–1317": "1238–1317",
    "1243–1333": "1243–1333",
    "1404–1502": "1404–1502",
    "1460–1539": "1460–1539",
    "1480–1600": "1480–1600",
    "1484–1564": "1484–1564",
    "1509–1609": "1509–1609",
    "1682–1755": "1682–1755",
    "1722–1762": "1722–1762",
    "1728–1809": "1728–1809",
    "1736–1822": "1736–1822",
    "1728–1751": "1728–1751",
    "1595–1671": "1595–1671",
    "1611–1681": "1611–1681",
    "1680–1752": "1680–1752",
    "1742–1783": "1742–1783",
    "1822–1904": "1822–1904",
    "18th Century": "18th Century",
    "13th Century": "13th Century",
    "14th Century": "14th Century",
    "15th Century": "15th Century",
    "16th Century": "16th Century",
    "17th Century": "17th Century",
    "18th–19th Century": "18th–19th Century",
    Mukhari: "Mukhari",
    Kedara: "Kedara",
    Anandabhairavi: "Anandabhairavi",
    Adi: "Adi",
    Bhakti: "Bhakti",
    Philosophy: "Philosophy",
    Social: "Social",
    catDasarapada: "Dasarapada",
    catDasarapadaDesc: "Devotional compositions set to classical music and rhythm, expressing devotion and social reform.",
    catMundige: "Mundige",
    catMundigeDesc: "Spiritual riddles and cryptic poems containing hidden esoteric and philosophical meanings.",
    catSuladi: "Suladi",
    catSuladiDesc: "Sophisticated musical structures incorporating multiple ragas and talas, unique to Haridasa tradition.",
    catUgabhoga: "Ugabhoga",
    catUgabhogaDesc: "Free-verse devotional poems sung without a strict rhythm, focusing on pure emotional expression.",
    catAll: "All Compositions",
    catAllDesc: "Browse and search through the entire library of Haridasa compositions.",
    backToCategories: "← Back to Categories",
    viewCategory: "View Category",
  },
  KN: {
    aboutEyebrow: "ನಮ್ಮ ಉಪಕ್ರಮ",
    aboutLead: "ಹರಿದಾಸರ ಸಂಪೂರ್ಣ ಕೃತಿಗಳನ್ನು ಡಿಜಿಟಲೀಕರಣಗೊಳಿಸಲು, ಅನುವಾದಿಸಲು ಮತ್ತು ಮುಂದಿನ ಪೀಳಿಗೆಗೆ ಸಂರಕ್ಷಿಸಲು ಒಂದು ಸಹಕಾರಿ ಪ್ರಯತ್ನ.",
    aboutTitle: "ಹರಿದಾಸ ಕೋಶ ಯೋಜನೆ",
    aiErrorMessage: "ಕ್ಷಮಿಸಿ, ನನ್ನ ಜ್ಞಾನ ಭಂಡಾರವನ್ನು ಸಂಪರ್ಕಿಸಲು ತೊಂದರೆಯಾಗುತ್ತಿದೆ.",
    aiMeaningfulWelcome: "ನಮಸ್ಕಾರ. ಹರಿದಾಸ ಕೋಶಕ್ಕೆ ಸ್ವಾಗತ. ನಾನು ನಿಮ್ಮ AI ಸಹಾಯಕ, ದಾಸ ಸಾಹಿತ್ಯದ ದೈವಿಕ ಕಾವ್ಯ ಮತ್ತು ತತ್ವಶಾಸ್ತ್ರವನ್ನು ಅನ್ವೇಷಿಸಲು ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ. ಹರಿದಾಸರ ಜೀವನ, ಕೀರ್ತನೆಯ ಅರ್ಥ ಅಥವಾ ಮಧ್ವ ತತ್ವಶಾಸ್ತ್ರದ ಬಗ್ಗೆ ನನ್ನನ್ನು ಕೇಳಿ.",
    ankita: "ಅಂಕಿತ",
    archivalEntry: "ದಾಖಲೆ ಪ್ರವೇಶ",
    askAiPrototypeWarning: "ಸೀಮಿತ ಅನುಷ್ಠಾನದಿಂದಾಗಿ AI ನಿರೀಕ್ಷೆಯಂತೆ ಕಾರ್ಯನಿರ್ವಹಿಸದಿರಬಹುದು.",
    brand: "ಹರಿದಾಸ ಕೋಶ",
    browseArchive: "ದಾಖಲೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    clearAll: "ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ",
    communityEngagement: "ಸಮುದಾಯದ ಪಾಲ್ಗೊಳ್ಳುವಿಕೆ",
    communityEngagementDesc: "ವಿದ್ವಾಂಸರು, ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ಭಕ್ತರು ಕಲಿಯಲು, ಚರ್ಚಿಸಲು ಮತ್ತು ಸಾಮೂಹಿಕ ತಿಳುವಳಿಕೆಗೆ ಕೊಡುಗೆ ನೀಡಲು ಉತ್ತೇಜಿಸುವ ವೇದಿಕೆಯನ್ನು ನಿರ್ಮಿಸುವುದು.",
    composer: "ಹರಿದಾಸರು",
    composerLabel: "ಹರಿದಾಸರು",
    deityLabel: "ಆರಾಧ್ಯ ದೈವ",
    ankitaLabel: "ಅಂಕಿತ",
    Unknown: "ಅಜ್ಞಾತ",
    composersPageDesc: "ಸರಳ ಹಾಡು ಮತ್ತು ಕಥೆಗಳ ಮೂಲಕ ಭಗವಂತನ ಪ್ರೀತಿಯನ್ನು ಹಂಚಿದ ಮಹಾನ್ ಸಂತರನ್ನು ಭೇಟಿ ಮಾಡಿ.",
    composersPageTitle: "ಹರಿದಾಸ ಪರಂಪರೆ",
    compositions: "ರಚನೆಗಳು",
    compositionsHeading: "ಹರಿದಾಸ ರಚನೆಗಳು",
    compositionsSubtitle: "ದ್ವೈತ ಸಂಪ್ರದಾಯದ ಭಕ್ತಿ ರಚನೆಗಳ ಅತಿದೊಡ್ಡ ಹುಡುಕಬಹುದಾದ ಸಂಗ್ರಹವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    contactBtn: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    contributeBtn: "ಈಗಲೇ ಕೊಡುಗೆ ನೀಡಿ",
    contributeSubtitle: "ಹರಿದಾಸರ ದೈವಿಕ ಜ್ಞಾನವನ್ನು ಸಂರಕ್ಷಿಸಲು, ಡಿಜಿಟಲೀಕರಣಗೊಳಿಸಲು ಮತ್ತು ಹಂಚಿಕೊಳ್ಳಲು ನಮ್ಮ ಮಿಷನ್ ಸೇರಿ.",
    contributeTitle: "ಹರಿದಾಸ ಕೋಶಕ್ಕೆ ಕೊಡುಗೆ ನೀಡಿ",
    dailyWisdom: "ದೈನಂದಿನ ಜ್ಞಾನ",
    dailyWisdomDesc: "ದಾಖಲೆಯಿಂದ ಇಂದಿನ ಒಂದು ತಾಜಾ ಭಕ್ತಿ ಚಿಂತನೆ.",
    defaultBio: "ಭಕ್ತಿ ಜ್ಞಾನದ ಮೂಲಕ ಸನ್ಮಾರ್ಗವನ್ನು ತೋರಿದ ಹರಿದಾಸರು.",
    deity: "ದೇವತೆ",
    digitalArchiving: "ಡಿಜಿಟಲ್ ದಾಖಲೀಕರಣ",
    digitalArchivingDesc: "ದುರ್ಲಭ ಹಸ್ತಪ್ರತಿಗಳನ್ನು ಮತ್ತು ವಿವಿಧ ಆವೃತ್ತಿಗಳನ್ನು ಒಂದುಗೂಡಿಸಿ, ಸುಲಭವಾಗಿ ಹುಡುಕಬಹುದಾದ ಮತ್ತು ಸಂಘಟಿತ ಡೇಟಾಬೇಸ್ ಆಗಿ ಪರಿವರ್ತಿಸುವುದು.",
    digitalPreservation: "ಡಿಜಿಟಲ್ ಸಂರಕ್ಷಣೆ",
    digitalPreservationDesc: "ಮಾಹಿತಿಯನ್ನು ಭವಿಷ್ಯದ ದೃಷ್ಟಿಯಿಂದ ಸಂಘಟಿಸಲಾಗಿದೆ ಮತ್ತು ಸಂಶೋಧಕರಿಗೆ ಲಭ್ಯವಾಗುವಂತೆ ಮಾಡಲಾಗಿದೆ.",
    dwAskAI: "AI ಅನ್ನು ಕೇಳಿ",
    dwDasarapada: "ದಾಸರಪದ",
    dwHaridasa: "ಹರಿದಾಸ",
    dwJourney: "ಪ್ರಯಾಣ",
    dwListen: "ಕೇಳಿ",
    dwRaga: "ರಾಗ",
    dwReadMeaning: "ಅರ್ಥ ಓದಿ",
    dwThought: "ಚಿಂತನೆ",
    englishTranslation: "ಇಂಗ್ಲಿಷ್ ಅನುವಾದ",
    exploreAllHaridasaru: "ಎಲ್ಲಾ ಹರಿದಾಸರನ್ನು ಅನ್ವೇಷಿಸಿ",
    exploreBtn: "ಅನ್ವೇಷಿಸಿ",
    exploreCompositions: "ರಚನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    exploreProfile: "ಪ್ರೊಫೈಲ್ ಅನ್ವೇಷಿಸಿ",
    featuredDesc: "ತಲೆಮಾರುಗಳಿಂದ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತಿರುವ ಪ್ರೀತಿಯ ಭಕ್ತಿ ರಚನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    featuredEyebrow: "ನಿಮಗಾಗಿ ಆಯ್ದವು",
    featuredTitle: "ವೈಶಿಷ್ಟ್ಯಪೂರ್ಣ ರಚನೆಗಳು",
    filters: "ಶೋಧಕಗಳು",
    getStartedBtn: "ಪ್ರಾರಂಭಿಸಿ",
    haridasa: "ಹರಿದಾಸ",
    heroDesc: "ಪರಿಶೀಲಿಸಿದ ಹರಿದಾಸರ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಅನ್ವೇಷಿಸಿ, ಕನ್ನಡ ಸಾಹಿತ್ಯ ಮತ್ತು ಅರ್ಥದೊಂದಿಗೆ ರಚನೆಗಳನ್ನು ಓದಿ ಮತ್ತು ದಾಸ ಸಾಹಿತ್ಯದ ಆಧ್ಯಾತ್ಮಿಕ ಆಳವನ್ನು ಅನ್ವೇಷಿಸಿ.",
    heroSub: "ಹರಿದಾಸ ಪರಂಪರೆಗೆ ಒಂದು ದ್ವಾರ.",
    heroTitle: "ಹರಿದಾಸ ಪರಂಪರೆಗೆ ಒಂದು ದ್ವಾರ.",
    historical: "ಐತಿಹಾಸಿಕ",
    insideArchive: "ದಾಖಲೆಯ ಒಳಗೆ",
    joinMissionDesc: "ನೀವು ವಿದ್ವಾಂಸರಾಗಿರಲಿ, ಗಾಯಕರಾಗಿರಲಿ ಅಥವಾ ಭಕ್ತರಾಗಿರಲಿ, ಈ ಬೆಳೆಯುತ್ತಿರುವ ಡಿಜಿಟಲ್ ಲೈಬ್ರರಿಗೆ ಕೊಡುಗೆ ನೀಡಲು ಹಲವು ಮಾರ್ಗಗಳಿವೆ.",
    joinMissionTitle: "ನಮ್ಮ ಮಿಷನ್ ಸೇರಿ",
    kannadaLyrics: "ಕನ್ನಡ ಸಾಹಿತ್ಯ",
    learnHistory: "ಇತಿಹಾಸ ಕಲಿಯಿರಿ",
    limit: "ಮಿತಿ",
    livingTradition: "ಒಂದು ಜೀವಂತ ಸಂಪ್ರದಾಯ",
    livingTraditionDesc: "ದ್ವೈತ ತತ್ವಶಾಸ್ತ್ರದ ತಳಹದಿಯ ಮೇಲೆ ಸ್ಥಾಪಿತವಾದ ಹರಿದಾಸ ಚಳುವಳಿಯು ಹಾರ್ದಿಕ ಭಕ್ತಿಯ ಮೂಲಕ ಆಧ್ಯಾತ್ಮಿಕ ಜ್ಞಾನವನ್ನು ಜನಸಾಮಾನ್ಯರಿಗೆ ತಲುಪಿಸಿತು.",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    methodologyDesc: "ರಚನೆಗಳ ಪವಿತ್ರತೆ ಮತ್ತು ನಿಖರತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ನಾವು ಕಟ್ಟುನಿಟ್ಟಾದ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಅನುಸರಿಸುತ್ತೇವೆ.",
    methodologyTitle: "ನಮ್ಮ ವಿಧಾನ",
    modernSeeker: "ಆಧುನಿಕ ಜಿಜ್ಞಾಸುಗಳಿಗೆ ಮಾರ್ಗದರ್ಶಿ",
    modernSeekerDesc: "ನೀವು ಈ ಪರಂಪರೆಗೆ ಹೊಸಬರಾಗಿದ್ದರೆ, ಕರ್ನಾಟಕ ಸಂಗೀತದ ಪಿತಾಮಹ ಎಂದು ಕರೆಯಲ್ಪಡುವ ಶ್ರೀ ಪುರಂದರದಾಸರ ಜೀವನದಿಂದ ಪ್ರಾರಂಭಿಸಲು ನಾವು ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ.",
    navLibrary: "ಗ್ರಂಥಾಲಯ",
    navComposers: "ಹರಿದಾಸರು",
    navConnections: "ಸಂಪರ್ಕಗಳು",
    navParampara: "ಪರಂಪರೆ",
    madhwacharyaBio: "ಶ್ರೀ ಮಧ್ವಾಚಾರ್ಯರು (೧೨೩೮–೧೩೧೭) ದ್ವೈತ ವೇದಾಂತದ ಸ್ಥಾಪಕರು. ಇವರು ಹರಿದಾಸ ಚಳುವಳಿಯ ಮೂಲ ಪ್ರೇರಣೆಯಾಗಿದ್ದು, ಶ್ರೀಕೃಷ್ಣನ ಮೇಲಿನ ಭಕ್ತಿಯ ತಾತ್ವಿಕ ಅಡಿಪಾಯವನ್ನು ಒದಗಿಸಿದರು.",
    paramparaSubtitle: "ಹರಿದಾಸ ಚಳುವಳಿಯು ೮೦೦ ವರ್ಷಗಳಲ್ಲಿ ಭಕ್ತಿಯ ಸುಂದರ ನದಿಯಂತೆ ಹೇಗೆ ಬೆಳೆಯಿತು ಎಂಬುದನ್ನು ಅನ್ವೇಷಿಸಿ.",
    eraFoundational: "ತಳಹದಿಯ ಯುಗ",
    eraGolden: "ಸುವರ್ಣ ಯುಗ",
    eraGoldenDesc: "ವಿಜಯನಗರದಲ್ಲಿ ಶ್ರೀ ಪುರಂದರದಾಸರು ಮತ್ತು ಶ್ರೀ ಕನಕದಾಸರ ನೇತೃತ್ವದಲ್ಲಿ ಚಳುವಳಿಯು ಪ್ರವರ್ಧಮಾನಕ್ಕೆ ಬಂದಿತು.",
    eraExpansion: "ವಿಸ್ತರಣಾ ಯುಗ",
    eraExpansionDesc: "ಶ್ರೀ ವಿಜಯದಾಸರು ಮತ್ತು ಜಗನ್ನಾಥದಾಸರು ಈ ಸಂದೇಶವನ್ನು ಪ್ರತಿ ಮನೆಮನೆಗೂ ತಲುಪಿಸಿದರು.",
    eraModern: "ಆಧುನಿಕ ಯುಗ",
    eraModernDesc: "ಡಿಜಿಟಲ್ ಸಂರಕ್ಷಣೆ ಮತ್ತು ಅಧ್ಯಯನದ ಮೂಲಕ ಈ ಸಂಪ್ರದಾಯವು ಇಂದಿಗೂ ಜಿಜ್ಞಾಸುಗಳಿಗೆ ಸ್ಫೂರ್ತಿ ನೀಡುತ್ತಿದೆ.",
    timelineStart: "೧೩ನೇ ಶತಮಾನ",
    timelineEnd: "ಇಂದಿನ ದಿನ",
    kidFriendlyMessage: "ಮಕ್ಕಳೇ! ಈ ಮಹಾನ್ ಸಂತರು ಹೇಗೆ ದೇವರನ್ನು ಹಾಡಿ ಹೊಗಳಿದರು ಎಂಬುದನ್ನು ನೋಡಲು ಈ ಕಮಲದ ಹಾದಿಯನ್ನು ಅನುಸರಿಸಿ!",
    eraFoundationalDesc: "ಶ್ರೀ ಮಧ್ವಾಚಾರ್ಯರು ಮತ್ತು ಮೊದಲ ಹರಿದಾಸರಾದ ಶ್ರೀ ನರಹರಿ ತೀರ್ಥರು ಈ ಬೀಜವನ್ನು ಬಿತ್ತಿದರು.",
    name: "ಕನ್ನಡ",
    carouselTitle1: "ವಿಸ್ತಾರವಾದ ಡಿಜಿಟಲ್ ಗ್ರಂಥಾಲಯ",
    carouselDesc1: "ಮಹಾನ್ ಹರಿದಾಸರು ರಚಿಸಿದ ನೂರಾರು ಅಧಿಕೃತ ದೇವರನಾಮಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.",
    carouselTitle2: "ಆಳವಾದ ಕನ್ನಡ ಮತ್ತು ಆಂಗ್ಲ ಅನುವಾದಗಳು",
    carouselDesc2: "ಪದದಿಂದ ಪದದ ಲಿಪ್ಯಂತರಣ ಮತ್ತು ಅನುವಾದಗಳೊಂದಿಗೆ ಆಳವಾದ ಅರ್ಥಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
    carouselTitle3: "ಹರಿದಾಸರ ಜೀವನ ಚರಿತ್ರೆಗಳು",
    carouselDesc3: "ಮಹಾನ್ ಸಂತರ ಶ್ರೀಮಂತ, ವಿವರವಾದ ಇತಿಹಾಸ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಪ್ರಯಾಣಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    carouselTitle4: "ಸಂಗೀತ ಪರಂಪರೆ",
    carouselDesc4: "ಸಂಗೀತಗಾರರು ಮತ್ತು ಸಂಶೋಧಕರಿಗೆ ಸೂಕ್ತವಾದ ಸಾಂಪ್ರದಾಯಿಕ ರಾಗ ಮತ್ತು ತಾಳಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    navHome: "ಮುಖಪುಟ",
    navAskAI: "AI ಕೇಳಿ",
    navComposers: "ಹರಿದಾಸರು",
    navDailyWisdom: "ದೈನಂದಿನ ಜ್ಞಾನ",
    navLibrary: "ಗ್ರಂಥಾಲಯ",
    sripadarajaru: "ಶ್ರೀ ಶ್ರೀಪಾದರಾಜರು",
    sripadarajaDesc: "ಶ್ರೀ ಶ್ರೀಪಾದರಾಜರು (1404–1502) ಅವರು ಮಹಾನ್ ಹರಿದಾಸರು ಮತ್ತು ಮುಳಬಾಗಿಲಿನ ಶ್ರೀಪಾದರಾಜ ಮಠದ ಪೀಠಾಧಿಪತಿಗಳಾಗಿದ್ದರು. ಇವರನ್ನು ಕರ್ನಾಟಕದಲ್ಲಿ ದಾಸ ಸಾಹಿತ್ಯ ಚಳುವಳಿಯ ಪ್ರವರ್ತಕರೆಂದು ಪರಿಗಣಿಸಲಾಗಿದೆ, ಇದು ಭಕ್ತಿ ಸಂಪ್ರದಾಯಕ್ಕೆ ಅಡಿಪಾಯವನ್ನು ಹಾಕಿತು. ಇವರು ಸುಳಾದಿ ಮತ್ತು ಉಗಾಭೋಗ ಎಂಬ ಕೀರ್ತನಾ ರೂಪಗಳನ್ನು ಪರಿಚಯಿಸಿದರು, ಇದು ದಾಸ ಪರಂಪರೆಯ ಭಕ್ತಿ ಸಂಗೀತವನ್ನು ಬಹಳವಾಗಿ ಶ್ರೀಮಂತಗೊಳಿಸಿತು. ಇವರು ಆಳವಾದ ವಿದ್ವಾಂಸರು, ತತ್ವಜ್ಞಾನಿಗಳು ಮತ್ತು ಶ್ರೀ ಬ್ರಹ್ಮಣ್ಯ ತೀರ್ಥರ ನೇರ ಶಿಷ್ಯರಾಗಿದ್ದರು, ತಮ್ಮ ಆಳವಾದ ಆಧ್ಯಾತ್ಮಿಕ ಒಳನೋಟಗಳಿಗೆ ಮತ್ತು ರಂಗವಿಠಲನ ಮೇಲಿನ ತೀವ್ರ ಭಕ್ತಿಗೆ ಹೆಸರುವಾಸಿಯಾಗಿದ್ದರು.",
    sripadarajaSloka: "ತಂ ವಂದೇ ನರಸಿಂಹತೀರ್ಥನಿಲಯಂ ಶ್ರೀವ್ಯಾಸರಾಟ್ ಪೂಜಿತಂ |\nಧ್ಯಾಯಂತಂ ಮನಸಾ ನೃಸಿಂಹಚರಣಮ್ ಶ್ರೀಪಾದರಾಜಂ ಗುರುಂ||",
    offset: "ಆಫ್‌ಸೆಟ್",
    open: "ತೆರೆಯಿರಿ",
    ourVision: "ನಮ್ಮ ದೃಷ್ಟಿಕೋನ",
    visionDesc: "ಪ್ರಾಚೀನ ಹಸ್ತಪ್ರತಿ ಸಂಪ್ರದಾಯಗಳು ಮತ್ತು ಆಧುನಿಕ ಜಿಜ್ಞಾಸುಗಳ ನಡುವಿನ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡಲು, ಸಮಗ್ರ ಹಾಗೂ ವಿಶ್ವಾಸಾರ್ಹವಾದ ಡಿಜಿಟಲ್ ಭಂಡಾರವನ್ನು ನಿರ್ಮಿಸುವುದು ನಮ್ಮ ಧ್ಯೇಯವಾಗಿದೆ.",
    whyWeExist: "ನಮ್ಮ ಅಸ್ತಿತ್ವದ ಉದ್ದೇಶ",
    whyWeExistDesc: "ದಾಸ ಸಾಹಿತ್ಯವು ಕೇವಲ ಸಾಹಿತ್ಯವಲ್ಲ; ಇದು ಶತಮಾನಗಳಿಂದ ಸಮುದಾಯಗಳನ್ನು ಬೆಳೆಸಿದ ಆಳವಾದ ಆಧ್ಯಾತ್ಮಿಕ, ಸಂಗೀತ ಮತ್ತು ತಾತ್ವಿಕ ಪರಂಪರೆಯಾಗಿದೆ. ಈ ಜ್ಞಾನವು ಸದಾ ಜೀವಂತವಾಗಿರಲು ನಾವು ಶ್ರಮಿಸುತ್ತಿದ್ದೇವೆ.",
    popularSearches: "ಜನಪ್ರಿಯ ಹುಡುಕಾಟಗಳು",
    practiceOfTheDay: "ದಿನದ ಅಭ್ಯಾಸ",
    proofreading: "ಪರಿಶೀಲನೆ",
    proofreadingDesc: "ಪಠ್ಯದ ನಿಖರತೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಸಾಹಿತ್ಯ ಮತ್ತು ಲಿಪ್ಯಂತರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    transcription: "ಲಿಪ್ಯಂತರ",
    transcriptionDesc: "ತಾಳೆಗರಿ ಹಸ್ತಪ್ರತಿಗಳನ್ನು ಡಿಜಿಟಲ್ ರೂಪಕ್ಕೆ ಲಿಪ್ಯಂತರ ಮಾಡಲು ಸಹಾಯ ಮಾಡಿ.",
    translation: "ಅನುವಾದ",
    translationDesc: "ಭಕ್ತಿಗೀತೆಗಳ ಅರ್ಥಗಳನ್ನು ಇಂಗ್ಲಿಷ್ ಮತ್ತು ಇತರ ಭಾಷೆಗಳಿಗೆ ಅನುವಾದಿಸಿ.",
    technicalSupport: "ತಾಂತ್ರಿಕ ಬೆಂಬಲ",
    technicalSupportDesc: "ನಮ್ಮ ಭಂಡಾರವನ್ನು ಸುಧಾರಿಸಲು ನಿಮ್ಮ ತಾಂತ್ರಿಕ ಪರಿಣತಿಯನ್ನು ನೀಡಿ.",
    prototypeWarning: "ಪ್ರಾಥಮಿಕ ಪ್ರೋಟೋಟೈಪ್ - ಕಾರ್ಯಗಳು ಸೀಮಿತವಾಗಿರಬಹುದು.",
    q: "ಹುಡುಕು",
    raga: "ರಾಗ",
    ragaLabel: "ರಾಗ",
    read: "ಓದಿ",
    readFullComposition: "ಪೂರ್ಣ ರಚನೆಯನ್ನು ಓದಿ",
    reflectionTitle: "ಚಿಂತನೆ",
    search: "ಹುಡುಕಿ",
    searchComposers: "ಹರಿದಾಸರನ್ನು ಹುಡುಕಿ...",
    "Ranga Vittala": "ರಂಗವಿಠಲ",
    "Purandara Vittala": "ಪುರಂದರ ವಿಠ್ಠಲ",
    "Vijaya Vittala": "ವಿಜಯ ವಿಠ್ಠಲ",
    "Jagannatha Vittala": "ಜಗನ್ನಾಥ ವಿಠ್ಠಲ",
    "Gopala Vittala": "ಗೋಪಾಲ ವಿಠ್ಠಲ",
    "Venugopala": "ವೇಣುಗೋಪಾಲ",
    "Kaginele Adikeshava": "ಕಾಗಿನೆಲೆ ಆದಿಕೇಶವ",
    "Bhimesha Krishna": "ಭೀಮೇಶಕೃಷ್ಣ",
    "Hayavadana": "ಹಯವದನ",
    "Prasanna Venkata": "ಪ್ರಸನ್ನ ವೆಂಕಟ",
    "mahipati": "ಮಹೀಪತಿ",
    Kedara: "ಕೇದಾರ",
    Anandabhairavi: "ಆನಂದಭೈರವಿ",
    Saurashtra: "ಸೌರಾಷ್ಟ್ರ",
    Mohana: "ಮೋಹನ",
    Kalyani: "ಕಲ್ಯಾಣಿ",
    Regupti: "ರೇಗುಪ್ತಿ",
    Bhairavi: "ಭೈರವಿ",
    Shankarabharana: "ಶಂಕರಾಭರಣ",
    Arabhi: "ಆರಭಿ",
    Surati: "ಸುರಟಿ",
    Shahana: "ಶಹನ",
    Madhyamavati: "ಮಧ್ಯಮಾವತಿ",
    Nadanamakriya: "ನಾದನಾಮಕ್ರಿಯೆ",
    Bhupala: "ಭೂಪಾಳ",
    Goula: "ಗೌಳ",
    "Brindavana Saranga": "ಬೃಂದಾವನ ಸಾರಂಗ",
    Mukhari: "ಮುಖಾರಿ",
    Bili: "ಬಿಳಿ",
    Gaulipantu: "ಗೌಳಿಪಂತು",
    "Yadukula Kambhoji": "ಯದುಕುಲ ಕಾಂಬೋದಿ",
    Adi: "ಆದಿ",
    Ata: "ಅಟ",
    Atte: "ಅಟ್ಟೆ",
    Chapu: "ಛಾಪು",
    "Trishra Chapu": "ತ್ರಿಶ್ರಛಾಪು",
    Triputa: "ತ್ರಿಪುಟ",
    Jhampe: "ಝಂಪೆ",
    Todi: "ತೋಡಿ",
    Khandajhampe: "ಖಂಡಝಂಪೆ",
    Poorvikalyani: "ಪೂರ್ವಿಕಲ್ಯಾಣಿ",
    statsAnkitas: "ಅಂಕಿತಗಳು",
    statsCompositions: "ರಚನೆಗಳು",
    statsHaridasas: "ಹರಿದಾಸರು",
    statsRagas: "ರಾಗಗಳು",
    tag: "ಟ್ಯಾಗ್",
    tailwindcss: "Tailwind CSS",
    globalAccess: "ಜಾಗತಿಕ ಪ್ರವೇಶ",
    global: "ಜಾಗತಿಕ",
    tala: "ತಾಳ",
    talaLabel: "ತಾಳ",
    "Ahudhadharu adhudhennni": "ಅಹುದಾದರಹುದೆನ್ನಿ",
    "Arigaadharu purva": "ಆರಿಗಾದರೂ ಪೂರ್ವ ಕರ್ಮ ಬಿಡದು",
    "Aritu nadeyalu beku narakayavettida mele": "ಅರಿತು ನಡೆಯಲು ಬೇಕು",
    "Aru hitavaru endu nambabeda": "ಆರು ಹಿತವರು ಎಂದು ನಂಬಬೇಡ",
    "Ava siriyali ninu enna marete": "ಆವ ಸಿರಿಯಲಿ ನೀನು ಎನ್ನ ಮರೆತೆ",
    "Badukidenu badukidenu bhava enage hingitu": "ಬದುಕಿದೆನು ಬದುಕಿದೆನು",
    "Bagilanu teredu seveyanu kodo hariye": "ಬಾಗಿಲನು ತೆರೆದು",
    "Baro krushnayya krushnayya": "ಬಾರೋ ಕೃಷ್ಣಯ್ಯ",
    "Bajare Hanumantam": "ಭಜರೇ ಹನುಮಂತಂ",
    "Bandevaya govinda setti": "ಬಂದೆವಯ್ಯ ಗೋವಿಂದಶೆಟ್ಟಿ",
    "Bandhu trijagake sri hariyallade mikka": "ಬಂಧು ತ್ರಿಜಗಕೆ ಶ್ರೀ ಹರಿ",
    "Beda beda elele": "ಬೇಡ ಬೇಡ ಎಲೆಲೆ",
    yearsOfHistory: "ಇತಿಹಾಸದ ವರ್ಷಗಳು",
    narahariTirthaDesc: "ಶ್ರೀ ನರಹರಿ ತೀರ್ಥರು (ಸು. 1243 – 1333) ಒಬ್ಬ ಪ್ರಖ್ಯಾತ ದ್ವೈತ ತತ್ವಜ್ಞಾನಿ, ರಾಜನೀತಿಜ್ಞ ಮತ್ತು ಹರಿದಾಸ ಪರಂಪರೆಯ ಜನಕ. ಇವರು ಶ್ರೀ ಮಧ್ವಾಚಾರ್ಯರ ನೇರ ಶಿಷ್ಯರಾಗಿದ್ದರು ಮತ್ತು ಮಧ್ವ ಪರಂಪರೆಯ ಎರಡನೇ ಪೀಠಾಧಿಪತಿಗಳಾಗಿ ಸೇವೆ ಸಲ್ಲಿಸಿದರು. ಹರಿದಾಸ ಸಂಪ್ರದಾಯವು ಜನಸಾಮಾನ್ಯರಿಗೆ ತಲುಪಲು ಕನ್ನಡದಲ್ಲಿ ಭಕ್ತಿ ಗೀತೆಗಳನ್ನು ರಚಿಸಿದ ಮೊದಲ ಹರಿದಾಸರು ಇವರು.",
    narahariTirthaSloka: "ಸಸೀತಾಮೂಲರಾಮಾರ್ಚಾ ಕೋಶೇ ಗಜಪತೇಃ ಸ್ಥಿತಾ |\nಯೇನಾನೀತಾ ನಮಸ್ತಸ್ಮೈ ಶ್ರೀಮನ್ನೃಹರಿಭಿಕ್ಷವೇ||",
    paramparaTitle: "ಪರಂಪರೆ",
    paramparaDesc: "ಶ್ರೀ ಮಧ್ವಾಚಾರ್ಯರು ಮತ್ತು ನರಹರಿ ತೀರ್ಥರಿಂದ ಪ್ರಾರಂಭವಾದ ೮೦೦ ವರ್ಷಗಳ ನಿರಂತರ ಭಕ್ತಿ ಚಳುವಳಿಯನ್ನು ಅನ್ವೇಷಿಸಿ.",
    paramparaHeading: "ಹರಿದಾಸ ಪರಂಪರೆ",
    paramparaLead: "ಸಂತರ ದಿವ್ಯ ಪರಂಪರೆಯ ಮೂಲಕ ಒಂದು ಪ್ರಯಾಣ",
    madhwacharyaru: "ಶ್ರೀ ಮಧ್ವಾಚಾರ್ಯರು",
    madhwacharyaSloka: "ಅಭ್ರಮಂ ಭಂಗರಹಿತಂ ಅಜಡಂ ವಿಮಲಂ ಸದಾ |\nಆನಂದತೀರ್ಥಮತುಲಂ ಭಜೇ ತಾಪತ್ರಯಾಪಹಂ||",
    narahariTirtha: "ಶ್ರೀ ನರಹರಿ ತೀರ್ಥರು",
    thirteenthCentury: "೧೩ನೇ ಶತಮಾನ",
    fourteenthCentury: "೧೪ನೇ ಶತಮಾನ",
    fifteenthCentury: "೧೫ನೇ ಶತಮಾನ",
    jagannathaDasa: "ಶ್ರೀ ಜಗನ್ನಾಥ ದಾಸರು",
    archivalIntegrity: "ದಾಖಲೆಗಳ ಸಮಗ್ರತೆ",
    archivalIntegrityDesc: "ರಚನೆಗಳ ಪವಿತ್ರತೆ ಮತ್ತು ನಿಖರತೆಯನ್ನು ಖಚಿತಪಡಿಸುವುದು.",
    scholarlyVetting: "ವิด್ವತ್ಪೂರ್ಣ ಪರಿಶೀಲನೆ",
    scholarlyVettingDesc: "ರಚನೆಗಳ ವಿದ್ವತ್ಪೂರ್ಣ ಸಂಶೋಧನೆ ಮತ್ತು ಪರಿಶೀಲನೆ.",
    vyasatirtha: "ಶ್ರೀ ವ್ಯಾಸತೀರ್ಥರು",
    vyasatirthaName: "ಶ್ರೀ ವ್ಯಾಸತೀರ್ಥರು",
    vyasatirthaDesc: "ವ್ಯಾಸರಾಯರು ಶ್ರೀಪಾದರಾಜರ ಶಿಷ್ಯರು. ಬಲ್ಲಣತೀರ್ಥರು ಇವರ ತಂದೆ. ತಾಯಿ ಲಕ್ಷ್ಮೀದೇವಿ. ಇವರ ಹುಟ್ಟು ಹೆಸರು ಯತಿರಾಜ. ಶ್ರೀ ಬ್ರಹ್ಮಣ್ಯತೀರ್ಥರು ಅವರಿಗೆ ಸನ್ಯಾಸ ದೀಕ್ಷೆಯನ್ನಿತ್ತು ವ್ಯಾಸತೀರ್ಥರೆಂದು ಕರೆದರು. ಸಾಳುವ ನರಸಿಂಹನೂ ಸೇರಿದಂತೆ ಆರು ಮಂದಿ ವಿಜಯನಗರದ ಅರಸರುಗಳಿಗೆ ಇವರು ರಾಜಗುರುಗಳಾಗಿದ್ದರು. ಕೃಷ್ಣದೇವರಾಯನ ಕುಹೂಯೋಗವನ್ನು ನಿವಾರಿಸಿ ರಾಜಗೌರವವನ್ನು ಪಡೆದರು. ಸಂಸ್ಕೃತ-ಕನ್ನಡ ಉಭಯ ಭಾಷೆಗಳಲ್ಲಿ ಪ್ರಕಾಂಡ ಪಂಡಿತರಾಗಿದ್ದರು. 'ಕೃಷ್ಣ', 'ಶ್ರೀಕೃಷ್ಣ', 'ಸಿರಿಕೃಷ್ಣ', 'ಮುದ್ದುಕೃಷ್ಣ'—ಇವರ ಅಂಕಿತಗಳು. ಮಧ್ವತತ್ತ್ವ ಪ್ರಸಾರದ ಉದ್ದೇಶದಿಂದ ಹರಿದಾಸದೀಕ್ಷೆ ಪಡೆದರು. ದಾಸಕೂಟದ ರಚನೆ ಇವರ ಒಂದು ಮಹತ್ತ್ವದ ಸಾಧನೆ. ವಾದಿರಾಜ, ಪುರಂದರ, ಕನಕರು ದಾಸಕೂಟದ ಪ್ರಮುಖರು. ೧೪೪೭ ಮತ್ತು ೧೫೩೯ ಈ ಕಾಲಾವಧಿಯಲ್ಲಿ ಬಾಳಿ ಬದುಕಿದ್ದರು.",
    vyasatirthaSloka: "ಅರ್ಥಿಕಲ್ಪಿತಕಲ್ಪೋಽಯಂ ಪ್ರತ್ಯರ್ಥಿಗಜಕೇಸರೀ |\nವ್ಯಾಸತೀರ್ಥಗುರುರ್ಭೂಯಾದಸ್ಮದಿಷ್ಟಾರ್ಥ ಸಿದ್ಧಯೇ||",
    purandaraDasa: "ಶ್ರೀ ಪುರಂದರದಾಸರು",
    purandaraDasaru: "ಶ್ರೀ ಪುರಂದರ ದಾಸರು",
    purandaraDasaDesc: "ಕರ್ನಾಟಕ ಸಂಗೀತದ ಪಿತಾಮಹ, ಭಕ್ತಿ ಮಾರ್ಗವನ್ನು ಸರಳ ಕೀರ್ತನೆಗಳ ಮೂಲಕ ಬೋಧಿಸಿದವರು.",
    purandaraDasaSloka: "ಮನ್ಮನೋಭೀಷ್ಟ ವರದಂ ಸರ್ವಾಭೀಷ್ಟ ಫಲಪ್ರದಂ |\nಪುರಂದರ ಗುರಂ ವಂದೇ ದಾಸಶ್ರೇಷ್ಠ ದಯಾನಿಧಿಮ್||",
    kanakaDasa: "ಶ್ರೀ ಕನಕದಾಸರು",
    kanakaDasaru: "ಶ್ರೀ ಕನಕ ದಾಸರು",
    kanakaDasaDesc: "ಭಕ್ತ ಕವಿ, ಸಮಾಜ ಸುಧಾರಕ, ಜಾತಿ ಪದ್ಧತಿಯನ್ನು ವಿರೋಧಿಸಿ ಭಕ್ತಿ ಮಾರ್ಗವನ್ನು ಜನಸಾಮಾನ್ಯರಿಗೆ ತಲುಪಿಸಿದವರು.",
    kanakaDasaSloka: "ಯಮಾಂಶಸ್ಯ ಪರಾಭಕ್ತ್ಯಾ ಸುಪ್ರಸನ್ನೋ ಹರಿಃ ಸ್ವಯಂ |\nಯಸ್ಯಾಚಾರ್ಯೋ ವ್ಯಾಸರಾಯಃ ತಂ ವಂದೇ ಕನಕಾಭಿಧಂ||",
    vijayaDasa: "ಶ್ರೀ ವಿಜಯದಾಸರು",
    vijayaDasaru: "ಶ್ರೀ ವಿಜಯ ದಾಸರು",
    vijayaDasaDesc: "ಹರಿದಾಸ ಸಾಹಿತ್ಯದ ಪ್ರಮುಖ ಕವಿ, ಇವರು ಸುಮಾರು ೨೫,೦೦೦ ದೇವರನಾಮಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ.",
    vijayaDasaSloka: "ಅಜ್ಞಾನ ತಿಮಿರಚ್ಛೇದಂ ಬುದ್ಧಿ ಸಂಪತ್ಪ್ರದಾಯಕಮ್ |\nವಿಜ್ಞಾನಂ ವಿಮಲಂ ಶಾಂತಂ ವಿಜಯಾಖ್ಯಂ ಗುರುಂ ಭಜೇ||",
    gopalaDasaSloka: "ಆಗತಾದಿ ತ್ರಿಕಾಲಜ್ಞಾಮ್ ಆಗಮಾರ್ಥ ವಿಶಾರಧಮ್ |\nತ್ಯಾಗ ಭೋಗ ಸಮಾಯುಕ್ತಮ್ ಭಾಗಣ್ಣಾರ್ಯ ಗುರುಮ್ ಭಜೇ||",
    gopalaDasaru: "ಶ್ರೀ ಗೋಪಾಲ ದಾಸರು",
    gopalaDasaDesc: "ಶ್ರೀ ಗೋಪಾಲ ದಾಸರು (1721–1769), ಇವರ ಮೊದಲ ಹೆಸರು ಭಾಗಣ್ಣ. ಇವರು ಹರಿದಾಸ ಪರಂಪರೆಯ ಪ್ರಮುಖ ಸಂತರು ಮತ್ತು ಶ್ರೀ ವಿಜಯ ದಾಸರ ಶಿಷ್ಯರಾಗಿದ್ದರು. 'ಗೋಪಾಲ ವಿಠಲ' ಎಂಬ ಅಂಕಿತದಲ್ಲಿ ಇವರು ಅನೇಕ ಕೃತಿಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ. ಜಗನ್ನಾಥ ದಾಸರಿಗೆ ತಮ್ಮ ಆಯುಷ್ಯವನ್ನು ದಾನ ಮಾಡಿದ ಮಹಾನ್ ಮಹಿಮೆ ಇವರದ್ದಾಗಿದೆ.",
    jagannathaDasaru: "ಶ್ರೀ ಜಗನ್ನಾಥ ದಾಸರು",
    jagannathaDasaDesc: "ಶ್ರೀ ಜಗನ್ನಾಥ ದಾಸರು (೧೭೨೮-೧೮೦೯) ಹರಿದಾಸ ಸಾಹಿತ್ಯದ ಅತ್ಯಂತ ಪ್ರಮುಖ ಸಂತ-ಕವಿಗಳಲ್ಲಿ ಒಬ್ಬರು. ಇವರು ಬರೆದ 'ಹರಿಕಥಾಮೃತಸಾರ' ಮತ್ತು 'ಹರಿನಾಮಾವಳಿ' ದ್ವೈತ ಸಿದ್ಧಾಂತದ ಪ್ರಮುಖ ಕೃತಿಗಳಾಗಿವೆ.",
    jagannathaDasaSloka: "ಜಲಾಶ್ರೇಷ್ಠನಿಭಾಕಾರಂ ಜಗದೀಶಪದಾಶ್ರಯಮ್ |\nಜಗತೀತಲವಿಖ್ಯಾತಂ ಜಗನ್ನಾಥಗುರುಂ ಭಜೇ||",
    mohanaDasaru: "ಶ್ರೀ ಮೋಹನ ದಾಸರು",
    helavanakatteGiriyamma: "ಹೆಳವನಕಟ್ಟೆ ಗಿರಿಯಮ್ಮ",
    srinivasaDasaru: "ಶ್ರೀನಿವಾಸ ದಾಸರು",
    lakshmipatiDasaru: "ಲಕ್ಷ್ಮೀಪತಿ ದಾಸರು",
    madhwapatiDasaru: "ಮಧ್ವಪತಿ ದಾಸರು",
    venkateshaDasaru: "ವೆಂಕಟೇಶ ದಾಸರು",
    narahariDasaru: "ನರಹರಿ ದಾಸರು",
    govindaDasaru: "ಗೋವಿಂದ ದಾಸರು",
    ugabhogaNarayanaDasaru: "ಉಗಾಭೋಗ ನಾರಾಯಣ ದಾಸರು",
    venugopalaDasaru: "ವೇಣುಗೋಪಾಲ ದಾಸರು",
    vishnuDasaru: "ವಿಷ್ಣು ದಾಸರು",
    krishnapriyaDasaru: "ಕೃಷ್ಣಪ್ರಿಯ ದಾಸರು",
    mohanaDasaDesc: "ಶ್ರೀ ಮೋಹನ ದಾಸರು (೧೭೨೮-೧೭೫೧) ಹರಿದಾಸ ಪರಂಪರೆಯ ಒಬ್ಬ ಪ್ರಮುಖ ಸಂತ-ಕವಿಗಳು. ಇವರು 'ಮೋಹನ ವಿಠಲ' ಎಂಬ ಅಂಕಿತನಾಮದಲ್ಲಿ ದೇವರನಾಮಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ. ತುಂಗಭದ್ರಾ ನದಿಯಲ್ಲಿ ಮುಳುಗಿ ಆತ್ಮಹತ್ಯೆ ಮಾಡಿಕೊಳ್ಳಲು ಯತ್ನಿಸಿದಾಗ ಶ್ರೀ ವಿಜಯದಾಸರು ಇವರನ್ನು ರಕ್ಷಿಸಿ, ಸಾಕಿ ಹರಿದಾಸ ದೀಕ್ಷೆ ನೀಡಿದರು.",
    mohanaDasaSloka: "ಮೋಹಭಯ ದು:ಖಾದಿದೂರಂ ಲೋಹಲೋಷ್ಠ ಸಮೇಕ್ಷಣಂ |\nಮಾಹಿತಾಂಘ್ರಿ ಸರೋಜಭೃಂಗಂ ಮೋಹನಾರ್ಯ ಗುರುಂ ಭಜೇ||",
    subbannaDasaru: "ಶ್ರೀ ಕಲ್ಲೂರು ಸುಬ್ಬಣ್ಣ ದಾಸರು",
    subbannaDasaDesc: "ಕಲ್ಲೂರು ಸುಬ್ಬಣ್ಣ ದಾಸರು (೧೮ನೇ ಶತಮಾನ) ವಿಜಯದಾಸರ ಪ್ರಮುಖ ಶಿಷ್ಯರು ಮತ್ತು ವ್ಯಾಸವಿಠಲ ಎಂಬ ಅಂಕಿತನಾಮದಲ್ಲಿ ಕೀರ್ತನೆಗಳನ್ನು ರಚಿಸಿದ ಪ್ರಸಿದ್ಧ ಹರಿದಾಸರು.",
    subbannaDasaSloka: "ವ್ಯಾಸವಿಠ್ಠಲ ದಾಸೇಂದ್ರಂ ಜ್ಞಾನಭಕ್ತಿ ಪರಾಯಣಮ್ |\nವಿಜಯದಾಸ ಕೃಪಾಪಾತ್ರಂ ನಮಾಮಿ ಕಲ್ಲೂರು ಹರಿದಾಸಮ್||",
    raghavendraDasaru: "ಶ್ರೀ ರಾಘವೇಂದ್ರ ತೀರ್ಥರು",
    raghavendraDasaDesc: "ಮಂತ್ರಾಲಯದಲ್ಲಿ ಸಶರೀರ ಬೃಂದಾವನ ಪ್ರವೇಶಿಸಿದ ಜಗದ್ಗುರುಗಳು, ಪರಮ ಪೂಜ್ಯ ತಪಸ್ವಿಗಳು ಹಾಗೂ ವಿದ್ವಾಂಸರು.",
    raghavendraDasaSloka: "ಪೂಜ್ಯಾಯ ರಾಘವೇಂದ್ರಾಯ ಸತ್ಯಧರ್ಮ ರತಾಯಚ |\nಭಜತಾಂ ಕಲ್ಪವೃಕ್ಷಾಯ ನಮತಾಂ ಕಾಮಧೇನವೇ||",
    satyabodhaDasaru: "ಶ್ರೀ ಸತ್ಯಬೋಧ ತೀರ್ಥರು",
    satyabodhaDasaDesc: "ಉತ್ತರಾದಿ ಮಠದ ಪರಮ ಪೂಜ್ಯ ಪೀಠಾಧಿಪತಿಗಳು, ಮಹಾನ್ ತಪಸ್ವಿಗಳು ಹಾಗೂ ಜ್ಞಾನಿಗಳು.",
    satyabodhaDasaSloka: "ನೈವೇದ್ಯಗವಿಷಂ ರಾಮೇ ವೀಕ್ಷ್ಯ ತದ್ಭುಕ್ತಿಭಾಕ್ ಗುರುಃ |\nಯೋಽದರ್ಶಯದ್ರವಿಂ ರಾತ್ರೌ ಸತ್ಯಬೋಧೋಽಸ್ತು ಮೇ ಮುದೇ||",
    harapanahalliBhimavva: "ಹರಪನಹಳ್ಳಿ ಭೀಮವ್ವ",
    harapanahalliBhimavvaDesc: "ಹರಪನಹಳ್ಳಿ ಭೀಮವ್ವ (೧೯ನೇ ಶತಮಾನ) ಹರಿದಾಸ ಪರಂಪರೆಯ ಒಬ್ಬ ಪ್ರಮುಖ ಮಹಿಳಾ ಸಂತ-ಕವಿಗಳು. ಇವರು 'ಭೀಮೇಶ ಕೃಷ್ಣ' ಎಂಬ ಅಂಕಿತನಾಮದಲ್ಲಿ ಅನೇಕ ಕೀರ್ತನೆಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ.",
    harapanahalliBhimavvaSloka: "ನಾರದಾದಾಪ್ತ ಸದ್ಬೋಧಾಂ ಸಾಧ್ವೀ ಸಾಹಿತ್ಯ ಕಾರಿಣೀಂ |\nಭೀಮೇಶ ಕೃಷ್ಣ ನಿರತಾಂ ವಂದೇ ಭೀಮವ್ವ ಮಾತರಂ||",
    mahipatiDasaru: "ಮಹೀಪತಿ ದಾಸರು",
    mahipatiDasaDesc: "ಕಾಖಂಡಕಿ ಶ್ರೀ ಮಹೀಪತಿ ದಾಸರು (೧೬೧೧-೧೬೮೧) ಹರಿದಾಸ ಸಾಹಿತ್ಯದ ಅತ್ಯಂತ ವಿಶಿಷ್ಟ ಸಂತ-ಕವಿಗಳು. ಇವರು ಕನ್ನಡ, ಮರಾಠಿ, ಉರ್ದು ಮತ್ತು ಸಂಸ್ಕೃತ ಭಾಷೆಗಳಲ್ಲಿ ಕೃತಿಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ.",
    mahipatiDasaSloka: "ಜಗದ್ಗುರುಂ ಕೃಪಾ ಸಿಂಧುಂ ಶರಣಾಗತ ವತ್ಸಲಮ್ |\nಭಕ್ತಮಾನಸ ಸಂಚಾರಂ ಮಹಿಪತಿ ಗುರುಂ ಭಜೇ||",
    praneshaDasaru: "ಶ್ರೀ ಪ್ರಾಣೇಶ ದಾಸರು",
    praneshaDasaDesc: "ಪ್ರಾಣೇಶ ದಾಸರು (೧೭೩೬-೧೮೨೨) ಜಗನ್ನಾಥದಾಸರ ಪ್ರಮುಖ ಶಿಷ್ಯರು ಮತ್ತು ಪ್ರಾಣೇಶ ವಿಠಲ ಎಂಬ ಅಂಕಿತನಾಮದಲ್ಲಿ ಕೀರ್ತನೆಗಳನ್ನು ರಚಿಸಿದ ಪ್ರಸಿದ್ಧ ಹರಿದಾಸರು.",
    praneshaDasaSloka: "ಪ್ರಾಣಪತಿ ಪದದ್ವಂದ್ವ ಪಂಕಜಾಸಕ್ತಮಾನಸಂ |\nಶಮಾದಿಗುಣ ಸಂಯುಕ್ತಂ ಶ್ರೀಪ್ರಾಣೇಶ ಗುರುಂ ಭಜೇ||",
    prasannaVenkataDasaru: "ಪ್ರಸನ್ನ ವೆಂಕಟ ದಾಸರು",
    prasannaVenkataDasaDesc: "ಪ್ರಸನ್ನ ವೆಂಕಟ ದಾಸರು (೧೬೮೦-೧೭೫೨) ಬಾಗಲಕೋಟೆಯ ಪ್ರಸಿದ್ಧ ಹರಿದಾಸರು. ಇವರು ಪ್ರಸನ್ನ ವೆಂಕಟ ಎಂಬ ಅಂಕಿತನಾಮದಲ್ಲಿ ಕೀರ್ತನೆಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ.",
    prasannaVenkataDasaSloka: "ಶ್ರೀ ಶಾತ್ಪ್ರಾಪ್ತ ಸುವಿಜ್ಞಾನಮ್ ಶ್ರೀಶೈಕ ನಿರತಂ ಸದಾ |\nಪ್ರಸನ್ನ ವೇಂಕಟಾರ್ಯೋಮೇ ಭೂಯಾತ್ ಸರ್ವಾರ್ಥ ಸಿದ್ಧಯೇ||",
    vadirajaTirtharu: "ಶ್ರೀ ವಾದಿರಾಜ ತೀರ್ಥರು",
    vadirajaTirthaDesc: "'ಹಯವದನ' ಶ್ರೀ ವಾದಿರಾಜರ ಅಂಕಿತ. ವ್ಯಾಸರಾಯರ ಶಿಷ್ಯರಾದ ವಾದಿರಾಜರು ದ. ಕನ್ನಡ ಜಿಲ್ಲೆಯ ಕುಂದಾಪುರಕ್ಕೆ ಸಮೀಪದ ಹೂವಿನ ಕೆರೆಯಲ್ಲಿ ಜನಿಸಿದರು (೧೪೮೦) ಸಂಸ್ಕೃತ, ಕನ್ನಡ, ತುಳುವಿನಲ್ಲಿ ಗ್ರಂಥರಚನೆ ಮಾಡಿದವರು. 'ರುಕ್ಮಿಣೀಶ ವಿಜಯ', 'ಯುಕ್ತಿಮಲ್ಲಿಕಾ' 'ಸರಸಭಾರತೀವಿಲಾಸ' ಮುಂತಾದ ಸಂಸ್ಕೃತ ಗ್ರಂಥಗಳನ್ನು ರಚಿಸಿರುವರು. ಕನ್ನಡದಲ್ಲಿ 'ವೈಕುಂಠವರ್ಣನೆ', 'ಲಕ್ಷ್ಮೀಶೋಭಾನೆ', 'ಸ್ವಪ್ನಪದ', 'ಕೀಚಕ ವಧ', 'ಕೇಶವನಾಮ' ಇತ್ಯಾದಿ ಕೃತಿಗಳನ್ನು ರಚಿಸಿದ್ದಾರೆ. ಅವರ ಕೀರ್ತನೆಗಳಲ್ಲಿ ಸಾಮಾಜಿಕ ಕಳಕಳಿ, ಆರ್ತಭಾವ ಸ್ಪಷ್ಟವಾಗಿ ಗೋಚರಿಸುತ್ತವೆ. ಉಡುಪಿಯ ಅಷ್ಟ ಮಠಗಳಲ್ಲಿ ಒಂದಾದ ಸೋದೆ ಮಠದ ಪೀಠಾಧಿಪತಿಗಳಾದ ಅವರು ಅಷ್ಟ ಮಠಗಳ ಆಡಳಿತ ವ್ಯವಸ್ಥೆಯನ್ನು ರೂಪಿಸಿ ಪೂಜೆಗೆ ಎರಡು ವರ್ಷಗಳ ಕಾಲಾವಧಿಯ 'ಪರ್ಯಾಯ' ಪದ್ಧತಿಯನ್ನು ಏರ್ಪಡಿಸಿದವರು.",
    vadirajaTirthaSloka: "ತಪೋ ವಿದ್ಯಾ ವಿರಕ್ತ್ಯಾದಿ ಸದ್ಘುಣೌ ಘಾಕರಾನಹಮ್ |\nವಾದಿರಾಜ ಗುರೂನ್ ವಂದೇ ಹಯಗ್ರೀವ ದಯಾಶ್ರಯನ್||",
    narahariTirtharu: "ಶ್ರೀ ನರಹರಿ ತೀರ್ಥರು",
    reveredHaridasa: "ಪೂಜ್ಯ ಹರಿದಾಸರು.",
    "1238–1317": "೧೨೩೮–೧೩೧೭",
    "1243–1333": "೧೨೪೩–೧೩೩೩",
    "1404–1502": "೧೪೦೪–೧೫೦೨",
    "1460–1539": "೧೪೬೦–೧೫೩೯",
    "1480–1600": "೧೪೮೦–೧೬೦೦",
    "1484–1564": "೧೪೮೪–೧೫೬೪",
    "1509–1609": "೧೫೦೯–೧೬೦೯",
    "1682–1755": "೧೬೮೨–೧೭೫೫",
    "1722–1762": "೧೭೨೨–೧೭೬೨",
    "1728–1809": "೧೭೨೮–೧೮೦೯",
    "1736–1822": "೧೭೩೬–೧೮೨೨",
    "1728–1751": "೧೭೨೮–೧೭೫೧",
    "1595–1671": "೧೫೯೫–೧೬೭೧",
    "1611–1681": "೧೬೧೧–೧೬೮೧",
    "1680–1752": "೧೬೮೦–೧೭೫೨",
    "1742–1783": "೧೭೪೨–೧೭೮೩",
    "1822–1904": "೧೮೨೨–೧೯೦೪",
    "18th Century": "೧೮ನೇ ಶತಮಾನ",
    "13th Century": "೧೩ನೇ ಶತಮಾನ",
    "14th Century": "೧೪ನೇ ಶತಮಾನ",
    "15th Century": "೧೫ನೇ ಶತಮಾನ",
    "16th Century": "೧೬ನೇ ಶತಮಾನ",
    "17th Century": "೧೭ನೇ ಶತಮಾನ",
    "18th–19th Century": "೧೮-೧೯ನೇ ಶತಮಾನ",
    missionEyebrow: "ಧ್ಯೇಯ",
    missionTitle: "ಭಕ್ತಿಯ ಧ್ವನಿಯನ್ನು ಸಂರಕ್ಷಿಸುವುದು",
    missionDesc: "ಹರಿದಾಸ ಕೋಶವು ಕರ್ನಾಟಕದ ಹರಿದಾಸರ ಭಕ್ತಿ ಸಾಹಿತ್ಯ ಮತ್ತು ದಾಸ ಸಾಹಿತ್ಯದ ಸಂರಕ್ಷಣೆ ಮತ್ತು ಅಧ್ಯಯನಕ್ಕಾಗಿ ಮೀಸಲಾದ ಒಂದು ಡಿಜಿಟಲ್ ಭಂಡಾರವಾಗಿದೆ.",
    foundations: "ಮೂಲ ಅಡಿಪಾಯಗಳು",
    verifiedKeertanas: "ಪರಿಶೀಲಿಸಿದ ಕೀರ್ತನೆಗಳು",
    discoverStories: "ಕಥೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    studyStructures: "ರಚನೆಗಳ ಅಧ್ಯಯನ",
    archiveTitle: "ಡಿಜಿಟಲ್ ದಾಖಲೆ",
    archiveDesc: "ಪರಿಶೀಲಿಸಿದ ಕೀರ್ತನೆಗಳು, ಸುಳಾದಿಗಳು ಮತ್ತು ಉಗಾಭೋಗಗಳ ಸಂಪೂರ್ಣ ಸಂಗ್ರಹವನ್ನು ಸಾಹಿತ್ಯದೊಂದಿಗೆ ಓದಿ.",
    scholarlyTitle: "ವಿದ್ವತ್ಪೂರ್ಣ ಪರಿಶೀಲನೆ",
    scholarlyDesc: "ಪರಂಪರೆಯ ವಿದ್ವಾಂಸರಿಂದ ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟ ಅನುವಾದಗಳು, ಪದಶಃ ಅರ್ಥಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಹಿನ್ನೆಲೆಯನ್ನು ಪ್ರವೇಶಿಸಿ.",
    keyFeatures: "ಪ್ರಮುಖ ಲಕ್ಷಣಗಳು",
    structuredPath: "ಆಧ್ಯಾತ್ಮಿಕ ಜ್ಞಾನಕ್ಕೆ ಒಂದು ವ್ಯವಸ್ಥಿತ ಮಾರ್ಗ",
    pathDesc: "ಭಕ್ತಿ ಆರಾಧನೆ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಸಂಶೋಧನೆ ಎರಡನ್ನೂ ಸುಲಭಗೊಳಿಸಲು ಈ ಕೋಶವನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
    historicalAuthenticity: "ಐತಿಹಾಸಿಕ ಅಧಿಕೃತತೆ",
    historicalDesc: "ಪ್ರತಿ ರಚನೆಯನ್ನು ತಾಳೆಗರಿ ಹಸ್ತಪ್ರತಿಗಳು ಮತ್ತು ಆಪರೂಪದ ಮುದ್ರಿತ ಆವೃತ್ತಿಗಳೊಂದಿಗೆ ಹೋಲಿಸಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    musicalHeritage: "ಸಂಗೀತ ಪರಂಪರೆ",
    musicalHeritageDesc: "ಶ್ರೀ ಪುರಂದರದಾಸರು ರೂಪಿಸಿದ ರಾಗ, ತಾಳ ಮತ್ತು ಮೂಲಭೂತ ಸಂಗೀತ ಶಿಕ್ಷಣದ ತಳಹದಿಯನ್ನು ಅಧ್ಯಯನ ಮಾಡಿ.",
    universalAccess: "ಸಾರ್ವತ್ರಿಕ ಪ್ರವೇಶ",
    universalAccessDesc: "ಪ್ರಪಂಚದಾದ್ಯಂತದ ಸಂಶೋಧಕರು, ಗಾಯಕರು ಮತ್ತು ಭಕ್ತರಿಗಾಗಿ ಉಚಿತ, ಹುಡುಕಬಹುದಾದ ಮತ್ತು ವ್ಯವಸ್ಥಿತವಾದ ಮಾಹಿತಿ.",
    haridasaruTitle: "ಹರಿದಾಸರು",
    saintsSoil: "ಈ ಮಣ್ಣಿನ ಸಂತರು",
    saintsSoilDesc: "ನಾಡಿನಾದ್ಯಂತ ಸಂಚರಿಸಿ ಭಕ್ತಿ ಮತ್ತು ಶರಣಾಗತಿಯ ಸಂದೇಶವನ್ನು ಹರಡಿದ ಸುಧಾರಕರನ್ನು ಪರಿಚಯ ಮಾಡಿಕೊಳ್ಳಿ.",
    devotionalContext: "ಭಕ್ತಿ ಹಿನ್ನೆಲೆ",
    exploreByDeity: "ದೇವತೆಗಳ ಮೂಲಕ ಹುಡುಕಿ",
    deityDesc: "ಹರಿದಾಸರ ಕೀರ್ತನೆಗಳು ಮುಖ್ಯವಾಗಿ ಪಂಢರಪುರದ ಶ್ರೀ ಪಾಂಡುರಂಗ ವಿಠ್ಠಲ ಮತ್ತು ಭಗವಾನ್ ವಿಷ್ಣುವಿನ ವಿವಿಧ ರೂಪಗಳನ್ನು ಕುರಿತಾಗಿವೆ.",
    vittala: "ವಿಠ್ಠಲ",
    krishna: "ಕೃಷ್ಣ",
    rama: "ರಾಮ",
    lakshmi: "ಲಕ್ಷ್ಮಿ",
    narasimha: "ನರಸಿಂಹ",
    hanuman: "ಹನುಮಂತ",
    srinivasa: "ಶ್ರೀನಿವಾಸ",
    shiva: "ಶಿವ",
    Vittala: "ವಿಠ್ಠಲ",
    Krishna: "ಕೃಷ್ಣ",
    Rama: "ರಾಮ",
    Lakshmi: "ಲಕ್ಷ್ಮಿ",
    Narasimha: "ನರಸಿಂಹ",
    Hanuman: "ಹನುಮಂತ",
    Srinivasa: "ಶ್ರೀನಿವಾಸ",
    Shiva: "ಶಿವ",
    startingPoint: "ಆರಂಭದ ಬಿಂದು",
    journeyKeertana: "ಒಂದೇ ಕೀರ್ತನೆಯೊಂದಿಗೆ ನಿಮ್ಮ ಕೀರ್ತನ ಯಾತ್ರೆ ಪ್ರಾರಂಭಿಸಿ",
    journeyDesc: "ಪ್ರತಿಯೊಂದು ಕೀರ್ತನೆಯೂ ಹರಿದಾಸರ ಭಕ್ತಿ ಜಗತ್ತಿಗೆ ಪ್ರವೇಶ ದ್ವಾರವಾಗಿದೆ. ಯಾವುದಾದರೂ ಒಂದು ಕೃತಿಯಿಂದ ನಿಮ್ಮ ಅನ್ವೇಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
    biographiesCount: "ಜೀವನ ಚರಿತ್ರೆಗಳು",
    authenticLyrics: "ಅಧಿಕೃತ ಸಾಹಿತ್ಯ",
    philosophicalMeanings: "ತಾತ್ವಿಕ ಅರ್ಥಗಳು",
    categorization: "ವರ್ಗೀಕರಣ",
    academicDevotional: "ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಭಕ್ತಿ",
    "Vyasa Kuta": "ವ್ಯಾಸಕೂಟ",
    "Dasa Kuta": "ದಾಸಕೂಟ",
    "Udupi Krishna": "ಉಡುಪಿ ಕೃಷ್ಣ",
    "Vittala Keertana": "ವಿಠ್ಠಲ ಕೀರ್ತನೆ",
    "Haridasa Namavali": "ಹರಿದಾಸ ನಾಮಾವಳಿ",
    catDasarapada: "ದಾಸರಪದಗಳು",
    catDasarapadaDesc: "ಶಾಸ್ತ್ರೀಯ ರಾಗ ಮತ್ತು ತಾಳಕ್ಕೆ ಹೊಂದಿಕೆಯಾದ ಭಕ್ತಿ ಪ್ರಧಾನ ಕೀರ್ತನೆಗಳು.",
    catMundige: "ಮುಂಡಿಗೆಗಳು",
    catMundigeDesc: "ಗೂಢಾರ್ಥ ಮತ್ತು ತಾತ್ವಿಕ ರಹಸ್ಯಗಳನ್ನು ಒಳಗೊಂಡಿರುವ ಆಧ್ಯಾತ್ಮಿಕ ಒಗಟುಗಳು.",
    catSuladi: "ಸುಳಾದಿಗಳು",
    catSuladiDesc: "ಹರಿದಾಸ ಪರಂಪರೆಗೆ ವಿಶಿಷ್ಟವಾದ, ಬಹು ರಾಗ ಮತ್ತು ತಾಳಗಳನ್ನು ಒಳಗೊಂಡಿರುವ ಪ್ರೌಢ ರಚನೆಗಳು.",
    catUgabhoga: "ಉಗಾಭೋಗಗಳು",
    catUgabhogaDesc: "ತಾಳದ ನಿಯಮವಿಲ್ಲದೆ ಭಾವಪ್ರಧಾನವಾಗಿ ಹಾಡಲಾಗುವ ಭಕ್ತಿ ಮತ್ತು ನೀತಿಯ ಮುಕ್ತ ಕಾವ್ಯಗಳು.",
    catAll: "ಎಲ್ಲಾ ಕೃತಿಗಳು",
    catAllDesc: "ಹರಿದಾಸರ ಎಲ್ಲಾ ಕೃತಿಗಳನ್ನು ಒಂದೇ ಕಡೆ ಅನ್ವೇಷಿಸಿ ಮತ್ತು ಹುಡುಕಿ.",
    backToCategories: "← ವಿಭಾಗಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    viewCategory: "ವಿಭಾಗವನ್ನು ನೋಡಿ"
  }
};

const LanguageContext = createContext({
  lang: 'EN',
  setLang: (lang: string) => {},
  t: (key: string) => ''
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState('EN');

  useEffect(() => {
    const savedLang = localStorage.getItem('haridasa_lang');
    if (savedLang === 'EN' || savedLang === 'KN') {
      setLangState(savedLang);
    }
  }, []);

  const setLang = (newLang: string) => {
    if (newLang === 'EN' || newLang === 'KN') {
      setLangState(newLang);
      localStorage.setItem('haridasa_lang', newLang);
    }
  };
  
  const t = useMemo(() => (key: string) => {
    const translation = (translations as any)[lang]?.[key];
    if (!translation) {
      // Don't warn for keys that look like raw text/titles (e.g. has spaces, starts with uppercase, or starts with bracket/parenthesis)
      const isDynamicKey = /\s/.test(key) || /^[A-Z]/.test(key) || /^[\[(]/.test(key);
      if (!isDynamicKey) {
        console.warn(`Missing translation for key: ${key}`);
      }
      return key;
    }
    return translation;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
