import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Batch adding Purandara Dasa compositions...');

  const composerId = 'purandara-dasa';
  
  // Fetch existing Ankita and Deity for Purandara Dasa
  let ankita = await prisma.ankita.findFirst({ where: { name: 'Purandara Vittala' } });
  if (!ankita) {
    ankita = await prisma.ankita.create({ data: { name: 'Purandara Vittala' } });
  }

  let deity = await prisma.deity.findFirst({ where: { name: 'Vittala' } });
  if (!deity) {
    deity = await prisma.deity.create({ data: { name: 'Vittala' } });
  }

  const compositionTitles = [
    "aanalEkara", "AbhimAnavEke", "AcAravillada", "AcAriyarembavara", "AcyutAnanta gOvinda hari",
    "acyutAnanta gOvindanemba", "Ada hOdalle", "ADa hOgalu", "ADa hOgONa", "Adaddella oLide",
    "adarindEnu bala", "Adi varAhana", "Adida ranga", "AdidanO ranga", "AdidanOkuLiya",
    "Adisu nI", "AgalAgali rangayya", "AgalE kAyabEkO", "agali sairisalAradI", "ajnAnigaLa kUDe",
    "akaTakaTa nissAra", "akka ettaNa", "akka nandagOpana", "alli nODalu rAma", "aLuvudyAtako ranga",
    "ambegAlikkuda banda", "ambiga nA ninna", "amma enna", "amma nimma maga", "amma nimma manegaLalli",
    "ande nirNaya", "andE nirNayisidaru", "andigallade", "andinda nA", "Ane banditammamma",
    "anganeyarella", "angi toTTEne", "anjabEDa bEDalo", "anjal yAtake manave", "anjikin yAtakayya",
    "antakana dUtarige", "anu kAlavu", "anubhavadaDugeya", "anudinadali bandu", "anya satiya",
    "apamAnavAdare", "aparaadi naanalla", "appappA nI", "Ara hAraisidarEnuNTu", "Ara maganenda",
    "AraNAgradi", "Aratiya beLagire", "aravindAlayE tAyE", "ArEna mADuvaru", "ArEnu mADuvaru Arinda",
    "ArEnu mADuvaru tA", "Arige moreyiDalo", "ariyadavarige", "ariyade bandevu", "ariyaru",
    "ArOgaNeya", "Aru badukidarayya", "Aru badukidarEnu", "Aru bandavaravva", "Aru bAraru",
    "Aru hitavaru", "Aru olidarEnu", "Aru sari ninage", "Atana pADuve", "Ava kula",
    "Ava kulaavAdarEnu", "AvAga nene", "AvanAvanu kAiva", "bA bA ranga", "bA gumma",
    "baDava ninagobbara", "badukidenu", "bagebage AdagaLelli", "bAi baDikarinda", "bailA bvige",
    "bailige bailAgidu", "baiyirO baiyirO", "bAla krSNane", "balavu balave", "banda nODi",
    "bandadellaa barali", "bandanEne ranga", "bande rangayya", "bandeyA pariNAmage", "bandu nindiha",
    "baNNisalaLave ninna", "baNNisi gOpi", "bara bEkO", "bAramma ele", "bAramma nAvibbarADuva",
    "bAravva bhAgIrathi", "bArayya manege", "bArayya ranga", "bArayya vEnkaTakrSNa", "bArayya venkaTaramaNa",
    "bArE gOpyamma", "baride duruviriyEkamma", "baride hOyitu", "baride nI", "bArige ninna",
    "bArO bArayya", "bArO brahmAdi", "bArO munisEtake", "bArO namma", "bArO nInenna",
    "bavvu bandidalla", "bEDa manave", "bEDa para sati", "bEDavenne nInu", "bEDavO brahma",
    "bEne tALalAre", "bhaagyada lakshmi baarammaa", "bhAgyada lakSmI", "bhakutara sEveya", "bhaNDanAdenu",
    "bhangAraviDa", "bhAratI dEvi tAye", "bhArati dEviya nene", "bhAratIshane enna", "bhASe hInara",
    "bhaya nivAraNavu", "bhayasamaya", "bhraSTAdaru", "bhUSaNakke bhUSaNa", "biDe ninna",
    "billegAranu", "binnahake bAyillavayya", "brahmAdigaLu", "brahmAnandada", "brAhmaNanendare",
    "brahmNDadoLage", "bUci bandide", "buddhi hELe", "buddhi mAtu", "buddhivantanalla",
    "buttiya kaTTO", "candava nODire", "candracooDa", "candracUDa shiva", "candrakAviyaniTTu",
    "ceNDanADuta", "chi chiEdara", "chI haLi", "cikkavanE ivanu", "cinte yAkO",
    "cinte yAtakO", "citta suddiyillada", "cittaisida vyAsarAya", "Dambhaka bhaktige", "dAnavana kondaddalla",
    "Dangurava sAri", "daNiya nODidEnO", "dAra maga", "dAra maganamma", "dArenendaro rangayya",
    "dAri yAvudayya", "dAriya tOro", "dAriyEnidake murAri", "dAsa shESAdivAsa", "dAsanentAguvenu",
    "dAsanna mADikO", "dAsara nindisa", "dAsu bArisutide", "daya mADO", "dayamaaDO dayamaaDO",
    "dEhavEke", "dEva banda", "dEva banda namma", "dEvakI kanda", "dEvaki nandana",
    "dEvakiyudara", "dhAnya dorakitu", "dhanyanAde nA", "dharaNige doreyendu", "dharma dorakombuvade",
    "dharma shravaNa", "dharma shravaNa vidEtake", "dharmakke kai", "dharmavE jayavemba", "dharmavemba sambaLava",
    "dhUpAratiya nODuva banni", "dhUpAratiya nODuva banni namma", "drSTi ninna", "drSTi tAgite", "durita gajake",
    "dUru mADuvarEne", "dvArakApurada", "eccaradali naDe", "eccarike eccarike", "eccarike eccarike manave",
    "EkAratiya nODuva", "EkE cintisutiddi", "EkE cintisuve", "Eke daya bAradO", "Eke gOpAla",
    "EkE I dEhavanu", "EkE mUrkhanAdyO", "EkE ninagiSTu", "Eke nirdayanAguve", "Eke vrndAvana",
    "Ekenna I", "EkennoLintu", "ElayyA beLagAyitu", "Elayya shrIhari", "ele manave",
    "ELELu sharadhiyu", "Eli mosara", "ellAnu ballenembuviralla", "ellaru mADUvudu", "ellelli Adi",
    "elli beNNeya", "elli virATa", "elliruva tande", "elliruvanO ranga", "elliya mathurApurapu",
    "eLLUkALinaSTu", "elyADi bande", "Ena hELale", "eNAdaru", "enagondu mAtu",
    "enagoppa doreyu", "Enanittu meccisuveno", "EnaNNa ninagEnaNNa", "EnAyitO I janake", "EnAyitO ninage",
    "EnAyitu rangage", "endappi kombe", "endendu ninna", "endigAdiru", "endige dhanya",
    "endu ninna", "endu nODidaru", "Enembenobba", "EnendaLayya sIte", "EnendarEnu nInenna",
    "Enentolide", "EnEnu dAnava", "EnEnu mADidarEnu", "enagondu mAtu", "enna biTTu",
    "enna janma", "enna kaDehAyisuvudu", "enna manada", "enna rakSiso", "entahudO ninna",
    "enthA balavantanO", "enthA celuvage", "enthA gADigAranE", "enthA pApi", "entha pEDi",
    "enthA puNyave gOpi enthA", "enthA puNyave gOpi ninage", "enthA puNyave ninnadentha", "enthA saNNavane", "enthavanE gOpi",
    "enthavanenthavane", "Enu anumAna", "Enu bandyO", "Enu bAredeyo", "Enu bEDali",
    "Enu dhanyaLO lakumi", "Enu gatiyO", "Enu kautukavo", "Enu mADidarenu bhava", "Enu mADidarEnu hindina",
    "Enu mADuvudillavamma", "Enu maruLAdyamma", "Enu meccidele", "Enu myA rAvaNa", "Enu pELale",
    "Enu vratavEnu", "eraDu ondAgadu", "eravina sirige", "eSTAdaru munna", "eSTU duSTane",
    "eSTu hELidaru", "eSTu tALali", "Etara celuva", "etara kaTapaTi", "etta pOdanamma",
    "etti koLLe", "gaDigeya magaLe", "gajavadanaa bEDuvE", "gajuganADutalirdanu", "gaNDa banda",
    "gangA tIrada", "gangAdi sakala", "garuDa gamana", "garuva gambhIra", "garuva vyAtako",
    "geddeyO hanumanta", "ghaTikAcaladi ninta", "giLiyu panjara", "gobbiralu bEDavO", "gOkulAbdi candra",
    "gOkulada gOpiyaradEsu", "gOkuladali nAniralAre", "gOkuladoLagiralArevamma", "gOkuladoLagOrva", "gOkuladoLu ninna",
    "gollatErella kUDi", "gOpi ninna magagAgi", "gOpi ninna magagajjuvenamma", "gOpiya bhAgyavidu", "gOvinda ennirO",
    "gOvinda gOvinda", "gOvindA namO", "gOvindA ninnAnanda", "gOvinda rAma", "gOvindaa ninna",
    "gOvindana dhyAna", "guddidavane balla", "guDu guDiyanu", "gUDu sikkalillA", "gummana kareyadire",
    "gummanelliha", "guNavAyitenna", "gururAyara nambirO", "guruvina gulAmanAguva", "hA hA hA hA",
    "hAlu ukkidO", "hamsa ninnali", "haNNinante lakSaNa", "haNNu bandide janaru", "haNNu bandide koLLirO",
    "haNNu kombaru", "haNNu koNDanu", "haNNu tA beNNe tA", "hanuma namma tAyi", "hanumana bhIma",
    "hanumana matave", "hanumanta dEva", "hanumanta nI balu", "hari bhakuti", "hari bhakutiya",
    "hari caraNavemba", "hari darushanakAgi", "hari dinadali", "hari guNada", "hari hararu hEge",
    "hari hararu samarendu", "hari hari hari", "hari hari hariyendu", "hari hariyenalikke", "hari kathAmrta",
    "hari koTTa", "hari krpeyali", "hari kuNida", "hari naaraayaNa", "hari nAma",
    "hari nIne", "hari ninnolumeyu", "hari sarvOttamanendu", "hari smaraNe maaDO", "hari smaraNeyillada",
    "hari smarisi", "haricitta satya", "haridAsara sanga", "harikathA shravaNa", "harikathe kELuva",
    "haripAdaviralikke", "hariya bittare", "hariya dAsaraginnu", "hariya divya nAma", "hariya gati",
    "hariya neneyada", "hariya neneyirO", "hariya smaraNe", "hariyadhika", "hariyE kuNiyendu",
    "hariyE paradaiva", "hariyE sarvOttama", "hariyemba nAmAmrtada", "hariyendu manadalli", "hariyennu hariyennu",
    "hasiveyAgutide", "hatti giDada", "hEge mADabEkO", "hEge mADali", "hEge meccisali",
    "hEge uddhAra", "hEgira bEku", "hELabArade buddhiya krSNayyage", "hELabArade buddhiya ninna", "hELidare namma",
    "heNDadi prANa", "heNDiranALuvaLi", "heNNIgiccaisuvare", "hetta tAyi", "hEvavellihudayya",
    "hiDagO biDabEDa", "higguve yAkO", "hindilla svAmi", "hingeyirabEku", "hoDI nagAri",
    "holadi holeya", "holeya horagihane", "hommeyADalu bEDi", "hontakAri nInEve", "horaDutAne",
    "horaghOgi ADadir", "hosa pariyE", "hoyyO hoyyO Dangurava", "huccu hiDiyidu", "huccu kunni",
    "hushyUnna baNNada", "huva taruvara", "I grAmadali", "I jIvaviddu", "I mahiyoLage",
    "I pariya", "I sharIrada", "I siriya nambi", "I tanuva", "ibbarheNDara",
    "idakoLLi", "idE samaya", "idiryArO guruvE", "idu bhAgyavidu", "idu Enanga",
    "idu eNu nODe", "Iga mADelo", "Igale bhajisale", "IgaluppavaDisidaLu", "IkkalAre kai",
    "ikko navanItacOra", "ikO namma svAmi", "ille kuLitidda", "illE vaikuNTha", "illi namma",
    "illiralAre allige", "indirA ramaNa", "indra jAladavane", "indriyangaLa", "indu nAnEnu",
    "indu ninna", "indu shruti", "innAdaru hariya", "innAdaru ninage", "innEka yamana",
    "innEnu gatiyenagelO", "innU dayabArade", "innu puTTisidarayya", "inthA heNNina", "inthAtanu guruvAdaddu",
    "intinthAddellavu", "intu ninna", "intu vEdAntagaLalli", "inyAke yamana", "irabEku haridAsara",
    "irabEku illadirabEku", "irabEku iradira", "IsabEku iddu", "IselArene I", "iSTAdaru munna",
    "iSTu pApava", "Ita mukhya prANa", "ittattu Odi", "ivagEke parimaLa", "ivagEke shrngAra",
    "ivana hiDakoNDu", "jagadantaryAmi", "jagadOddhaaraNaa", "jaganmOhananE", "jaladhiya langhisidavage",
    "jAliya maravante", "jANa nInahudO", "janaka suta", "jAnakIramaNage", "janara naDade",
    "jatana mADO", "jaya jaya jaya", "jaya jaya jaya jaanakikaantaa", "jaya jaya karuNAkara", "jaya jaya shrI",
    "jaya mangaLa", "jaya mangaLam", "jaya pANDuranga", "jayatu gOkulavAsa", "jayatu kOdaNDa",
    "jayavade jayavade", "jEnu bandide", "jnAnavantage", "jnAnavonde sAku", "jO jO jO jO",
    "jO jO yashOdeya", "kadava muccidaLidako", "kAgada bandide", "kAge kAkA", "kAge kUgitalla",
    "kai mIri", "kaiya tOrO", "kAla kaLedevalla", "kaLavu kalisidemma", "kALi banda",
    "kAlige biddeno", "kALiya mardana", "kaliyugada mahimeyu", "kaliyugadalli hari", "kaliyugadoLu hari",
    "kaLLa sikkida", "kallu sakkare koLLiro", "kalyANam tulasi", "kamala jaadala", "kamala kOmala",
    "kamala sulOcana", "kANadiralAre", "kanakadAsana", "kanasu kaNDene", "kandA bEDavo",
    "kanda hAla", "kandana kANirEne", "kandanEke malagane", "kaNDavarante ennanu", "kaNDe kaNDe kaNDe",
    "kaNDe kaNDe rAjara", "kaNDe kaNDe svAmiya", "kaNDe kaNDenu", "kaNDE karuNAnidhya", "kaNDe nA kanasinali",
    "kaNDe nA uDupiya", "kaNDEnaa gOvindanaa", "kaNDu kaNDu", "kaNDu mana", "kangaLidyAtakO",
    "kangaLigOshavillavE", "kaNNAre kaNDenacyutana", "kaNNetti nODalu", "kaNNinoLage nODo", "kappuyennalu",
    "karava mugidanu", "karedare O", "karedu bhikSeya", "karmavE tArakavu", "karuNAbdi nInante",
    "karuNAkarane nI", "karuNAnidhiye Isha", "karuNisi kELo", "karuNisu narahari", "kAruNya mUrutiye",
    "kathA shravaNa", "kaTiyalli karaviTTanu", "kaTTabEku", "kAvadEva nInallade", "kAyabEkenna",
    "kAyalArenu ranga", "kELalollane", "kELE gOpi enna", "kELe gOpi gOpAla", "kELide ninnaya",
    "kELo gOpisabEDa", "kELO saccaritA", "keNDake oraLe", "kereya neeranu", "kereya nIranu",
    "kEshava mAdhava", "keTTenallo", "keTTidu kelasavella", "keTTu neNtara", "koDabahudE magana",
    "koDo koDo", "koDu bEga", "koDu bEga divyamati", "koDu kaNDya", "koDu koDu",
    "koDuva kartu", "koDuvudendu enna", "koLalanUduttA banda", "kOLi kUgitallA", "koLige biddiruva",
    "koLLEgAra ninna", "kOti hAge", "koTTa sAlava", "koTTAnu koTTAnu", "koTTavaru sariye",
    "koTTu hOgenna", "krSNa bArO", "krSNA ena bArade", "krSNa mantrava", "krSNa nAmava",
    "krSNamUrti kaNNa", "krSNana bhajipage", "krSNEdi mangaLam", "ksheeraabdi kannige", "kSIrAbdi kannike",
    "kUDi koNDADa", "kUgade usirikkade", "kuNidADO krSNa", "kuruDu nAyi", "kUsina kaNDIryA",
    "kUsu kaNDevamma", "kUsu kaNDIryA", "lakSmIkAnta bArO", "lAli lAli namma", "lAli lAli rangayyage",
    "lAlisadaLu magana", "langOTi baluvoLLedaNNa", "loDaka loDaka", "loLaloTTe ellA", "lOTa pATa",
    "mA majha bApurE", "mADabArade", "maddu mADalariye", "mAdhava madusUdana", "madhukara vrtti",
    "madhva madada", "madhva muniyE namma", "madhvarAya guru", "madhvarAyara dEvArcaneya", "madhvarAyara nenedu",
    "maDi maDi maDi", "mADida enna", "mADu sikkadallA", "maganendADisuvaLu", "mahadAdi dEva",
    "makkaLa mANikave", "makuTakkE mangaLa", "malagayya jalajanAbha", "malagi eddanu", "malava toLeya",
    "mAna bhangava", "mAna hIna", "manasu ninna", "mAnava janma", "manava nilisuvadu",
    "manava shOdhisa", "manave cancalamatiya", "mandagamane ivan", "mandamadiyO", "mandara",
    "maNDe bOLAda", "mandhara dhara dEva", "mandhara dharanu", "maneyoLagADO", "mangaLa mAramaNage",
    "mangaLa shrI", "mangaLam jaya", "mAnisaroLu", "manmatha janakana", "maNNinda kAya",
    "manuja sharIravidEnu", "mAnuSa janma", "maratiyEnO ranga", "marevareno hariya", "mareya bEDa",
    "mareya bEDa manavE", "mareyadale manadalli", "mareyadirale", "mareyadiru hariya", "mareyadiru shrIhariya",
    "marudanghrikisalaya", "maruLADavEkO", "maruLu mADi", "mArutane Elendu", "mArutavatAranIta",
    "matadoLage", "mAtige bArada", "matikeTTu kAlava", "mAyAvati", "mAye enna",
    "meccadiru I bhAgya", "meccanayya hari", "mella mellane", "mOs hOdenallO", "mOsa hOdanalla",
    "mosara suridu", "muddu koDo", "muddu koLLirO", "muddu tArO", "mUDha ballane",
    "mUgu saNNadu", "mukhyaprANa enna", "mukkA ninnoDane", "muLLu koneya", "munde bhalA",
    "munjAneyeddu", "murahara nagadhara", "mUrkharAdaru", "mUrutiyane nillisO", "musukha tegedare",
    "musure toLeyabhEku", "muTTa bArO", "muTTa bEDavo", "muTTi muTTi muTTi", "muttidAgira",
    "muttina gaNDana", "muyyakke muuyi", "nA Donkadare", "nA mADida karma", "nA munde",
    "nA ninna dhyAna", "nA ninna manake", "nA ninnoLanya", "naaraayaNaa", "nAcike goLa bEDa",
    "nADamAtu bEDa", "naDe pOpa", "naDedu bA", "naDumaneyoLagondu", "nageyu barutide",
    "naguvarallo rangayya", "naivEdyava koLLo", "nAlage nAlage", "nalidADe enna", "naLina nAbhana",
    "naLinajANDa", "nAma kIrtane", "namba bEDi", "nambadiru I", "nambi bhajisirO",
    "nambi keTTavar", "nambi keTTavar illavO", "nambide ninna pAda", "nambide ninna pAdava", "nambu kaNDya",
    "namma dEva", "nammappa summagiro", "nanda nandana", "nanda tanaya", "nandana kandana",
    "nandanandana bArO", "nanEke baDavanu", "nAnEke paradEshi", "nAnEnu mADidenO", "nAnu bEra",
    "naranda mEle", "narasimha mantravondiralu", "narasimhana pAda", "narasimhanembo", "naravarya bhImasEna",
    "nArAyaNa bArade", "nArAyaNa enna", "nArAyaNa ennirO", "nArayaNa gOvinda hari", "nArAyaNa gOvinda jaya",
    "nArAyaNA ninna nAmada", "nArAyaNa ninna nAmAmrtavanu", "nArAyaNa tE", "nArAyaNanemba nAmava nEmadi", "nArAyaNanemba nAmava nimma",
    "nArAyaNAya namO nAgEndra", "nArAyaNAya namO nArAyaNAya", "nArirannaLe", "nAyi bandadappa", "necca bEDa nI",
    "necca bEDa prANi", "neccadirI bhAgya", "neccadiru bekku", "neccanayya", "neenyaakO ninna",
    "nene bEku", "neneve nAnanyara", "nenevenu anudina", "neneyirO bhakta", "nenTanu saNNavanendu",
    "nI koDe", "nI tande nA bande", "nilla bEkayya", "nillo nillo", "nimma bhAgya",
    "nindakarira", "nInE acyuta", "nInE anAtha", "nInE ballidanO", "nInE dayA",
    "nInE dayALO", "nIne gati", "nInE gatiyenage", "nInEke kaDe", "nIniralu namagEtake",
    "nIniruLellidde", "ninna bhakutiyenu", "ninna dAsanAde", "ninna daya", "ninna dhyAnava",
    "ninna divya", "ninna maga", "ninna magana bAdhe", "ninna magana gAli", "ninna maganEnE",
    "ninna maganu", "ninna mahimeyannu", "ninna nAma", "ninna nAmava", "ninna nAmave",
    "ninna nAmaviddare", "ninna nambide nIrada", "ninna nambide nIraja", "ninna nODi", "ninna olumege",
    "ninnadu ninage", "ninnane nambi", "ninnane nambidEnu", "ninnanne nambide", "ninnAshrayisuvenu",
    "ninne nODi", "ninyAru pELanna", "nIre nI", "nityavalla anitya", "nODa bannirO",
    "nODa bAradu", "nODadiru para", "nODe gOpi gokuladoLu", "nODe gOpi nOde", "nODi daNiyavu",
    "nODirai kalpa", "nODirayya hanumantana", "nODu nODu nODu", "nODuvudE kaNNu", "oDeya hari",
    "ODi baarayya", "ollane vaidika", "ollanO shrI hari", "oLLEdoLLEdu", "oLLidI shakuna",
    "ombhattu bAgiloLu", "omme neneyalu", "ondalla eraDalla", "onde kUgaLate", "onde manadi",
    "ondE nAmadalaDgidavO", "ondE nAmavu", "oppisa sallado", "padumanaabha", "padumanAbhA",
    "pagaDi hAke", "pAlise enna", "pAlisemma muddu shArade", "panca mahApAdakige", "pankaja mukhiyarellaru",
    "pannagAdri pati", "pApi ballane", "pApigaLolagella", "pApOsu hOdudalla", "parAku bhImanendu",
    "parAku mADade", "paramAtma hEgihanendare", "patha naDeyadayya", "pati bhakuti", "pavaDisu paramAtmane",
    "pAvana nvapAvana", "pELalaLave ninna", "phalahAravanu mADo", "piLLangOviya celuva", "piNDANDadoLagina",
    "pOgabEDa", "pOgadiralo ranga", "pOge pOge", "pOguvuducitave", "pongoLalUdutiha",
    "pOpu hOgaNa", "prAcIna karmavu", "prANa nAtha pAlisO", "pUje yAtakO", "puNDarIka varada",
    "pUrva janmadali", "puTTidaveraDu", "puTTisa bEDalo", "raama mantrava japisO", "raama raama raama raama yenirO",
    "rAgi tandIryA", "rAjabhOgakintadhika", "rakSisu lOka", "rAma dEva", "rAma embuva",
    "rAma gOvinda", "rAma mantrava (version 1)", "rAma mantrava (version 2)", "rAma nAma", "rAma nAma pAyasakke",
    "rAma nAma ratna", "rAma nAmave", "rAma rAma", "rAma rAmennirO", "rAmakrSNaru manege",
    "ramaNanillada", "ranga banda", "ranga bArO krSNa", "ranga bArO pANDuranga", "ranga bArO ranga",
    "ranga dadhiya", "ranga koLalanUdalAgi", "ranga ranga", "ranga rathava", "rangana nODire",
    "ranganAyaka svAmi", "ranganolida", "rangayya ninna", "rokka eraDakku", "rtumati biDu",
    "ruNavemba sutakavu", "saddu mADalu", "saDeya samsAra", "sadharavallavo", "sAdhu janara",
    "sAdhu sajjana", "sAdhu sangavAgada", "sahisalArena gOpi", "sajjanara sanga", "sakala duritagaLa",
    "sakala graha bala", "sakalavellavu", "sAku sAkinnu", "sAku samsAra namaginnEtara", "sAku samsAra sajjAgilla",
    "sAku samsAra tereya", "salahO viTTala", "sAligarinnu", "sallado krSNa", "sAmAnyavalla shrI hari",
    "samsAravembanda", "sanditayya prAyavu", "sanna hejegaliTTu", "saNNava nam mAtu", "saNNavanendu nA",
    "saNNavanivanAramma", "santAna sarOrava", "saraswati nanna", "sAri bandane", "sarvAparAdhava",
    "satata gaNa nAtha", "saTeya samsra", "satige svatantrava", "satyam jagatidu", "satyavantarigidu",
    "satyavembude", "seraga biDO", "sEvakataneda ruci", "shaktanAdare", "sharaNambe vANi",
    "sharaNu bhArati dEvige", "sharaNu ninage", "sharaNu sakalOddhaara", "sharaNu sharaNu", "sharaNu sharaNu sharaNu",
    "sharaNu sharaNu shrI", "sharaNu sharaNu surEndra", "sharanu siddhi vinaayaka", "sharaNu vEnkaTaramaNa", "sharIrakke barudide",
    "shiva ninhEgAdyO", "shObhAna shObhAnave", "shObhavavE idu", "shree gaNanaatha, lambOdara", "shree raamacandra shrita",
    "shreenivaasa neenE", "shrI gaNanAtha", "shrI madhva ramaNa", "shrI madhvarAyara", "shrI tatvavAda",
    "shrIkAnta enagiSTu", "shrInivAsa enna", "shrInivAsananghari sEve", "shrInivAsanu banda", "shrIpatiyu namage",
    "shrIrAjita", "shrngAravAgide", "sikkadanele jANe", "sikkideyo elO", "simharoopanaada",
    "siTTu mADidaruNTe", "smaraNe ondE", "smariso sarvada", "smarisuva janakella", "snAnava mADiro",
    "sO-aham brahma", "sOhamenna bEDelO", "sOmakula vArinidhi", "sthaLavillavayya", "suddi kELamma",
    "sujnyeyindALa bEkaNNa", "sulabha pUjeya", "sulabhavallavo", "suLLu nammallillavayya", "summane baruvade",
    "summane dorakuvade", "summane kAlava", "summanevaiSNava", "summaniru manave", "summaniru summaniru",
    "sundara mUruti", "suNNavilla", "svAmi mukhya prANa nI", "tA honna", "tA paDEdu",
    "taamboolava koLLu", "taaraka bindigE", "tALa bEku", "tALiya haridu", "tALu tALelO",
    "tamboori meeTTidava", "tAmbUlava koLLO", "tanagilladA", "tangALi vashavallave", "tangi nODe",
    "tangig-hELida", "tanuva nIroLagittu", "tappugaLella nInobbbi", "tappugaLellava", "tArakka bindige",
    "taraLeranna", "tArammayya", "tArisO shrIhari", "tAttata dhimita", "tAyi tandeyenna",
    "tElisO illa", "tirupati vEnkaTaramaNa", "toLaladiru", "tOLu tOLu", "tUgidaLE rangana",
    "tuNDanivanu", "tunge mangaLa", "turukkaru karedare", "tutturu tUrendu", "ubbadiru",
    "udara vairAgyavidu", "uNalolle yAkO", "uppavaDisayya", "Ura dEvara", "Urige bandare",
    "UTakke bandevu", "vahvvAre meNasina", "vaidya banda", "vaidyana nAnariye", "vandisidvare",
    "vandisuvudAdiyali", "varagaLiddalli", "varaguru upadEsha", "vArijanAbhana", "varuSa kAraNavalla",
    "vAsake yOgyavalla", "vAsudEva ninna", "vAsudEvana caraNavanaja", "vAsudEvana nAmAvaLiya", "vAsudEvana nenedu",
    "venkaTaacalanilayam", "vEnkaTaramaNa vEdAnta", "vEnkaTaramaNane baarO", "vEnkaTEsha bEDikombe", "vEnkaTEsha dayamADO",
    "vEnkaTEsha ninna", "vENu nAda", "vidhAtru dEvategaLu", "vidhi niSEda", "vidurana bhAgyavidu",
    "vIra hanuma", "viSayada vicAra", "viTTala salahO", "vrndAvana dEvi", "vrndAvanadoLu ADuvan",
    "vrndAvanavE mandiravAgiha", "vyApAra namagAyitu", "vyarthavAyite", "vyarttavillavE", "yaadava nee baa",
    "yaarE ranganaa", "yadukula nandana", "yAke bandyO", "yAke gOkula", "yAke kaDekaNNinda",
    "yAke kakulAdi", "yAkE mUrkhanAdiyO", "yAke ninagiSTu", "yAke nirayanAde", "yama tanna",
    "yamana shAsana", "yamanelyo kANenendu", "yantra dorakitu", "yAra maganamma", "yAramma mAta",
    "yArE bandavaru", "yAretta pOdarEnu", "yAriddarEnayya", "yArige dUruvenO", "yArige mADdimyA",
    "yArige yAruNTu", "yAru ariyaro", "yAru baruvaru", "yAru biTTaru", "yashOde ninna",
    "yashOdeyamma", "yAtake nODuti", "yAtakke durAshi", "yAva karmavO", "yAvAgalu hElabArade"
  ];

  for (let i = 0; i < compositionTitles.length; i++) {
    const title = compositionTitles[i];
    const id = `purandara-${i + 1}`;
    await prisma.composition.upsert({
      where: { id: id },
      update: {
        title: title,
        firstLine: title,
        composerId: composerId,
        ankitaId: ankita.id,
      },
      create: {
        id: id,
        title: title,
        firstLine: title,
        lyrics: title, // Placeholder
        composerId: composerId,
        ankitaId: ankita.id,
        deityId: deity.id,
      },
    });
  }

  console.log(`✅ ${compositionTitles.length} Purandara Dasa compositions added/updated successfully!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
